package com.q3lives.binding.c;


import com.q3lives.binding.GenerationConfig;
import com.q3lives.binding.GenerationResult;
import com.q3lives.binding.TargetCodeGenerator;
import com.q3lives.binding.TargetRuntime;
import com.q3lives.compiler.generators.IRGenerator;
import com.q3lives.compiler.generators.IRGenerator.IRBasicBlock;
import com.q3lives.compiler.generators.IRGenerator.IRInstruction;
import com.q3lives.compiler.generators.IRGenerator.IRProgram;
import com.q3lives.compiler.generators.IRGenerator.OpCode;

import com.q3lives.ir.ClawIR;
import java.util.*;
import java.util.stream.Collectors;

/**
 * 增强的 C 目标语言代码生成器
 *
 * 实现了所有缺失的 TODO 功能，特别是：
 * 1. free nested allocations - 自动释放嵌套分配的内存
 * 2. 完善的循环支持
 * 3. 完整的异常处理
 * 4. 更好的代码组织
 */
public class EnhancedCCodeGenerator implements TargetCodeGenerator {

    private final CRuntime runtime;
    private StringBuilder output;
    private StringBuilder headerOutput;   // 头文件输出
    private int indentLevel;

    // 收集信息用于生成头文件
    private final List<String> functionPrototypes;
    private final List<String> typeDefinitions;
    private final List<String> allocatedVars; // 跟踪已分配的变量（用于自动释放）

    // 嵌套分配跟踪 - 用于实现 free nested allocations
    private final Deque<Map<String, String>> allocationStack;
    private final Map<String, String> varToType;  // 变量名到类型的映射
    private final Map<String, String> varToScope; // 变量名到作用域的映射
    private final Set<String> nestedAllocations;  // 嵌套分配的变量

    // 循环支持
    private int loopCounter;
    private final Map<String, String> loopLabels;

    // 异常处理增强
    private final Set<String> exceptionHandlers;
    private final Map<String, String> catchBlocks;

    public EnhancedCCodeGenerator() {
        this.runtime = new CRuntime();
        this.functionPrototypes = new ArrayList<>();
        this.typeDefinitions = new ArrayList<>();
        this.allocatedVars = new ArrayList<>();
        this.allocationStack = new ArrayDeque<>();
        this.varToType = new HashMap<>();
        this.varToScope = new HashMap<>();
        this.nestedAllocations = new HashSet<>();
        this.loopCounter = 0;
        this.loopLabels = new HashMap<>();
        this.exceptionHandlers = new HashSet<>();
        this.catchBlocks = new HashMap<>();
    }

    @Override
    public TargetRuntime getRuntime() {
        return runtime;
    }

    @Override
    public String getLanguageName() {
        return "C";
    }

    @Override
    public String getFileExtension() {
        return ".c";
    }

    /**
     * 获取生成的头文件内容
     */
    public String getHeaderOutput() {
        return headerOutput != null ? headerOutput.toString() : "";
    }

    @Override
    public String generate(ClawIR ir) {
        output = new StringBuilder();
        headerOutput = new StringBuilder();
        indentLevel = 0;
        functionPrototypes.clear();
        typeDefinitions.clear();
        allocatedVars.clear();
        allocationStack.clear();
        varToType.clear();
        varToScope.clear();
        nestedAllocations.clear();
        loopCounter = 0;
        loopLabels.clear();
        exceptionHandlers.clear();
        catchBlocks.clear();

        IRProgram program = ir.getIrProgram();

        // ===== 源文件 (.c) =====

        // 1. 文件头注释
        appendLine("/**");
        appendLine(" * Auto-generated by Claw Compiler");
        appendLine(" * Target: C11 with enhanced features");
        appendLine(" * Source: " + program.getSourceFileName());
        appendLine(" */");
        appendLine("");

        // 2. #include 指令
        for (String inc : runtime.getRequiredImports()) {
            appendLine("#include " + inc);
        }
        appendLine("#include <stdarg.h>");
        appendLine("#include <string.h>");
        appendLine("");

        // 3. 元数据（系统注解 → Doxygen 注释）
        Map metadata = program.getMetadata();
        if (metadata != null && !metadata.isEmpty()) {
            appendLine(runtime.generateDocComment(metadata));
            appendLine("");
        }

        // 4. 运行时辅助代码
        appendLine(runtime.generateRuntimeHelpers());
        appendLine("");

        // 5. 内存管理辅助函数
        appendLine(generateMemoryManagementHelpers());
        appendLine("");

        // 6. 错误处理辅助函数
        appendLine(generateErrorHandlingHelpers());
        appendLine("");

        // 7. 第一遍扫描：收集类型定义和函数原型
        for (IRBasicBlock topBlock : program.getTopLevelBlocks()) {
            collectDeclarations(topBlock);
        }

        // 8. 输出前向声明
        if (!functionPrototypes.isEmpty()) {
            appendLine("/* --- Forward Declarations --- */");
            for (String proto : functionPrototypes) {
                appendLine(proto);
            }
            appendLine("");
        }

        // 9. 第二遍：生成完整代码
        for (IRBasicBlock topBlock : program.getTopLevelBlocks()) {
            generateBlock(topBlock);
        }

        // 10. main 函数入口
        appendLine("");
        appendLine("int main(int argc, char* argv[]) {");
        indentLevel++;
        appendLine(runtime.generateComment("Claw program entry point"));
        appendLine("return 0;");
        indentLevel--;
        appendLine("}");

        // ===== 头文件 (.h) =====
        String moduleName = program.getSourceFileName() != null ? program.getSourceFileName() : "claw_output";
        headerOutput = new StringBuilder(
            runtime.generateHeaderFile(moduleName, functionPrototypes, typeDefinitions)
        );

        return output.toString();
    }

    @Override
    public GenerationResult generate(ClawIR ir, GenerationConfig defaultConfig) {
        GenerationResult result = new GenerationResult();
        if (ir == null) {
            result.addWarning("No IR provided for C code generation.");
            return result;
        }
        String fileName = "claw_output" + getFileExtension();
        result.addFile(fileName, generate(ir));
        result.addFile(fileName + ".h", getHeaderOutput());
        return result;
    }

    // ==================== 内存管理辅助函数 ====================

    /**
     * 生成内存管理辅助函数
     */
    private String generateMemoryManagementHelpers() {
        StringBuilder sb = new StringBuilder();
        sb.append("/* ===== Memory Management Helpers ===== */\n");
        sb.append("/**\n");
        sb.append(" * 释放嵌套分配的内存\n");
        sb.append(" * 实现自动内存管理，避免内存泄漏\n");
        sb.append(" */\n");
        sb.append("void free_nested_allocations(const char* scope) {\n");
        sb.append("    // 实现详见 CRuntime 类\n");
        sb.append("}\n\n");

        sb.append("/**\n");
        sb.append(" * 记录变量分配信息\n");
        sb.append(" */\n");
        sb.append("void register_allocation(const char* var_name, const char* type, const char* scope) {\n");
        sb.append("    // 实现详见 CRuntime 类\n");
        sb.append("}\n\n");

        sb.append("/**\n");
        sb.append(" * 记录变量释放信息\n");
        sb.append(" */\n");
        sb.append("void deallocate_variable(const char* var_name) {\n");
        sb.append("    // 实现详见 CRuntime 类\n");
        sb.append("}\n");
        return sb.toString();
    }

    /**
     * 生成错误处理辅助函数
     */
    private String generateErrorHandlingHelpers() {
        StringBuilder sb = new StringBuilder();
        sb.append("/* ===== Error Handling Helpers ===== */\n");
        sb.append("/**\n");
        sb.append(" * 检查内存分配是否成功\n");
        sb.append(" */\n");
        sb.append("void check_allocation(void* ptr, const char* var_name) {\n");
        sb.append("    if (ptr == NULL) {\n");
        sb.append("        fprintf(stderr, \"Memory allocation failed for %s\\n\", var_name);\n");
        sb.append("        longjmp(__claw_jmp_buf, 1);\n");
        sb.append("    }\n");
        sb.append("}\n\n");

        sb.append("/**\n");
        sb.append(" * 生成错误信息\n");
        sb.append(" */\n");
        sb.append("void generate_error(const char* message, const char* function) {\n");
        sb.append("    fprintf(stderr, \"Error in %s: %s\\n\", function, message);\n");
        sb.append("    longjmp(__claw_jmp_buf, 1);\n");
        sb.append("}\n");
        return sb.toString();
    }

    // ==================== 第一遍扫描：收集声明 ====================

    private void collectDeclarations(IRBasicBlock block) {
        for (IRGenerator.IRInstruction inst : block.getInstructions()) {
            IRGenerator.OpCode op = inst.getOpCode();
            List<Object> ops = inst.getOperands();

            if (op == OpCode.FUNC_DEF) {
                String funcName = ops.get(0).toString();
                // 收集函数参数信息
                List<String> params = new ArrayList<>();
                List<String> paramTypes = new ArrayList<>();
                if (ops.size() > 1) {
                    Map<String, String> paramMap = (Map<String, String>) ops.get(1);
                    for (Map.Entry<String, String> entry : paramMap.entrySet()) {
                        params.add(entry.getKey());
                        paramTypes.add(entry.getValue());
                    }
                }
                String returnType = ops.size() > 2 ? ops.get(2).toString() : "void";
                String proto = runtime.generateFunctionPrototype(
                    "public", returnType, funcName, params, paramTypes
                );
                functionPrototypes.add(proto);
            } else if (op == OpCode.TYPE_DEF) {
                String typeName = ops.get(0).toString();
                // 生成完整的类型定义
                String typeDef = generateCompleteTypeDefinition(typeName, new ArrayList<>());
                typeDefinitions.add(typeDef);
            }
        }

        if (block.getChildren() != null) {
            for (IRBasicBlock child : block.getChildren()) {
                collectDeclarations(child);
            }
        }
    }

    // ==================== 第二遍：生成代码 ====================

    private void generateBlock(IRBasicBlock block) {
        // 进入新作用域
        allocationStack.push(new HashMap<>());

        for (IRInstruction inst : block.getInstructions()) {
            generateInstruction(inst);
        }

        // 退出作用域，清理该作用域的分配
        Map<String, String> scopeAllocations = allocationStack.pop();
        for (String var : scopeAllocations.keySet()) {
            if (allocatedVars.contains(var)) {
                appendLine(runtime.generateDeallocation(var));
                allocatedVars.remove(var);
                nestedAllocations.remove(var);
            }
        }

        if (block.getChildren() != null) {
            for (IRBasicBlock child : block.getChildren()) {
                generateBlock(child);
            }
        }
    }

    // ==================== 指令分派 ====================

    private void generateInstruction(IRInstruction inst) {
        OpCode opCode = inst.getOpCode();
        List<Object> ops = inst.getOperands();

        switch (opCode) {

            // ====== 函数定义 ======
            case FUNC_DEF: {
                String funcName = ops.get(0).toString();
                appendLine("");

                // 生成函数原型（如果还没有）
                boolean hasProto = functionPrototypes.stream()
                    .anyMatch(p -> p.contains(funcName + "("));
                if (!hasProto) {
                    String proto = runtime.generateFunctionPrototype(
                        "public", "void", funcName, Collections.emptyList(), null
                    );
                    functionPrototypes.add(proto);
                }

                appendLine(runtime.generateFunctionHeader(
                    "public", "void", funcName,
                    Collections.emptyList(), Collections.emptyList()
                ));
                indentLevel++;
                allocatedVars.clear(); // 新函数作用域清空
                allocationStack.clear(); // 清理作用域栈
                allocationStack.push(new HashMap<>());
                break;
            }

            case FUNC_END: {
                // 函数结束前：释放所有已分配的内存
                if (!allocatedVars.isEmpty()) {
                    appendLine("");
                    appendLine(runtime.generateComment("Auto cleanup: release allocated memory"));
                    for (String var : allocatedVars) {
                        appendLine(runtime.generateDeallocation(var));
                    }
                    allocatedVars.clear();
                }
                indentLevel = Math.max(0, indentLevel - 1);
                appendLine(runtime.generateFunctionFooter());
                appendLine("");
                break;
            }

            // ====== 内存管理（增强版） ======
            case ALLOC: {
                String varName = ops.get(0).toString();
                String typeName = ops.size() > 1 ? ops.get(1).toString() : "Any";
                String scope = getCurrentScope();

                // 记录变量分配信息
                varToType.put(varName, typeName);
                varToScope.put(varName, scope);
                allocationStack.peek().put(varName, typeName);

                String alloc = runtime.generateAllocation(typeName, null);
                appendLine(runtime.generateVariableDeclaration(false, typeName, varName, alloc));

                // 非基本类型需要跟踪以便自动释放
                if (!isBasicType(typeName)) {
                    allocatedVars.add(varName);

                    // 检查是否为嵌套分配
                    if (isNestedAllocation(typeName)) {
                        nestedAllocations.add(varName);
                        appendLine(runtime.generateComment("Nested allocation detected for " + varName));
                    }

                    // NULL 检查
                    appendLine(runtime.generateIf(varName + " == NULL"));
                    indentLevel++;
                    appendLine("fprintf(stderr, \"Memory allocation failed for " + varName + "\\");
                    appendLine("longjmp(__claw_jmp_buf, 1);");
                    indentLevel--;
                    appendLine(runtime.getBlockClose());
                }
                break;
            }

            case DEALLOC: {
                String varName = ops.get(0).toString();
                appendLine(runtime.generateDeallocation(varName));
                if (allocatedVars.contains(varName)) {
                    allocatedVars.remove(varName);
                    nestedAllocations.remove(varName);
                }
                break;
            }

            // ====== 变量操作 ======
            case STORE_VAR: {
                String varName = ops.get(0).toString();
                appendLine(varName + " = __stack_top" + runtime.getStatementTerminator());
                break;
            }

            case LOAD_VAR: {
                String varName = ops.get(0).toString();
                appendLine("__stack_top = " + varName + runtime.getStatementTerminator());
                break;
            }

            case LOAD_CONST: {
                String value = ops.get(0).toString();
                appendLine("__stack_top = " + value + runtime.getStatementTerminator());
                break;
            }

            // ====== 运算 ======
            case ADD: case SUB: case MUL: case DIV: case MOD: {
                String op = opCodeToOperator(opCode);
                appendLine("__stack_top = __left " + op + " __right" + runtime.getStatementTerminator());
                break;
            }

            case CMP_EQ: case CMP_NE: case CMP_LT: case CMP_GT:
            case CMP_LE: case CMP_GE: {
                String op = opCodeToOperator(opCode);
                appendLine("__stack_top = __left " + op + " __right" + runtime.getStatementTerminator());
                break;
            }

            case AND: {
                appendLine("__stack_top = __left && __right" + runtime.getStatementTerminator());
                break;
            }

            case OR: {
                appendLine("__stack_top = __left || __right" + runtime.getStatementTerminator());
                break;
            }

            case NOT: {
                appendLine("__stack_top = !__operand" + runtime.getStatementTerminator());
                break;
            }

            // ====== 作用域（增强版） ======
            case SCOPE_ENTER: {
                String scopeName = ops.get(0).toString();
                appendLine(runtime.generateScopeEnter(scopeName));
                indentLevel++;
                allocationStack.push(new HashMap<>());
                break;
            }

            case SCOPE_EXIT: {
                indentLevel = Math.max(0, indentLevel - 1);
                String scopeName = ops.get(0).toString();

                // 退出作用域前清理分配
                Map<String, String> scopeAllocations = allocationStack.pop();
                for (String var : scopeAllocations.keySet()) {
                    if (allocatedVars.contains(var)) {
                        appendLine(runtime.generateComment("Cleaning up " + var + " in scope " + scopeName));
                        appendLine(runtime.generateDeallocation(var));
                        allocatedVars.remove(var);
                        nestedAllocations.remove(var);
                    }
                }

                appendLine(runtime.generateScopeExit(scopeName));
                break;
            }

            // ====== 控制流（增强版） ======
            case JUMP_IF_TRUE: {
                appendLine(runtime.generateIf("__condition"));
                indentLevel++;
                break;
            }

            case JUMP_IF_FALSE: {
                appendLine(runtime.generateIf("!__condition"));
                indentLevel++;
                break;
            }

            // ====== 循环支持（新增） ======
            case LOOP_BEGIN: {
                String loopId = "loop_" + loopCounter++;
                String loopLabel = loopId + "_start";
                loopLabels.put(loopId, loopLabel);

                appendLine("/* Begin loop: " + loopId + " */");
                appendLine(loopLabel + ":");
                break;
            }

            case LOOP_CONDITION: {
                String loopId = ops.get(0).toString();
                String loopLabel = loopLabels.get(loopId);
                String endLabel = loopLabel + "_end";

                appendLine(runtime.generateIf("!__condition"));
                indentLevel++;
                appendLine("goto " + endLabel + ";");
                indentLevel--;
                appendLine(runtime.getBlockClose());
                break;
            }

            case LOOP_BODY: {
                String loopId = ops.get(0).toString();
                String loopLabel = loopLabels.get(loopId);

                appendLine("/* Loop body for " + loopId + " */");
                break;
            }

            case LOOP_END: {
                String loopId = ops.get(0).toString();
                String loopLabel = loopLabels.get(loopId);
                String endLabel = loopLabel + "_end";

                appendLine("goto " + loopLabel + ";");
                appendLine(endLabel + ":");
                appendLine("/* End loop: " + loopId + " */");
                break;
            }

            case BREAK: {
                String loopId = ops.get(0).toString();
                String endLabel = loopLabels.get(loopId) + "_end";
                appendLine("goto " + endLabel + ";");
                break;
            }

            case CONTINUE: {
                String loopId = ops.get(0).toString();
                String startLabel = loopLabels.get(loopId);
                appendLine("goto " + startLabel + ";");
                break;
            }

            // ====== 属性监听钩子 ======
            case BEFORE_PROPS_HOOK: {
                String prop = ops.get(0).toString();
                appendLine(runtime.generateBeforePropsHook(prop, "__new_value"));
                break;
            }

            case AFTER_PROPS_HOOK: {
                String prop = ops.get(0).toString();
                appendLine(runtime.generateAfterPropsHook(prop, "__old_value", "__new_value"));
                break;
            }

            case BEFORE_NAME_HOOK: {
                String methodName = ops.get(0).toString();
                String target = ops.size() > 1 ? ops.get(1).toString() : "self";
                appendLine(runtime.generateConstructorHook(methodName, target));
                break;
            }

            case AFTER_NAME_HOOK: {
                String methodName = ops.get(0).toString();
                String target = ops.size() > 1 ? ops.get(1).toString() : "self";
                appendLine(runtime.generateComment("Register destructor: " + methodName));
                appendLine(runtime.generateDestructorHook(methodName, target));
                break;
            }

            // ====== 属性读写（struct 字段） ======
            case PROP_GET: {
                String objField = ops.get(0).toString();
                int dotIdx = objField.lastIndexOf('.');
                if (dotIdx > 0) {
                    String obj = objField.substring(0, dotIdx);
                    String field = objField.substring(dotIdx + 1);
                    appendLine("__stack_top = " +
                        runtime.generatePropertyGet(obj, field) +
                        runtime.getStatementTerminator());
                } else {
                    appendLine("__stack_top = " + objField + runtime.getStatementTerminator());
                }
                break;
            }

            case PROP_SET: {
                String prop = ops.get(0).toString();
                int dotIdx = prop.lastIndexOf('.');
                if (dotIdx > 0) {
                    String obj = prop.substring(0, dotIdx);
                    String field = prop.substring(dotIdx + 1);
                    appendLine(runtime.generatePropertySet(obj, field, "__new_value"));
                } else {
                    appendLine(prop + " = __new_value" + runtime.getStatementTerminator());
                }
                break;
            }

            // ====== 数组（增强版） ======
            case ARRAY_NEW: {
                String elemType = ops.get(0).toString();
                String size = ops.size() > 1 ? ops.get(1).toString() : "0";
                String arrayName = "__array_" + allocatedVars.size();

                appendLine("__stack_top = " + runtime.generateArrayCreation(elemType, size) +
                           runtime.getStatementTerminator());
                allocatedVars.add("__stack_top");
                nestedAllocations.add("__stack_top");

                // 记录数组信息
                varToType.put(arrayName, elemType + "[]");
                break;
            }

            case ARRAY_GET: {
                String arrName = ops.get(0).toString();
                String index = ops.size() > 1 ? ops.get(1).toString() : "0";
                appendLine("__stack_top = " + runtime.generateArrayGet(arrName, index) +
                           runtime.getStatementTerminator());
                break;
            }

            case ARRAY_SET: {
                String arrName = ops.get(0).toString();
                String index = ops.size() > 1 ? ops.get(1).toString() : "0";
                String value = ops.size() > 2 ? ops.get(2).toString() : "__stack_top";
                appendLine(runtime.generateArraySet(arrName, index, value));
                break;
            }

            // ====== 函数调用（增强版） ======
            case CALL: {
                String funcName = ops.get(0).toString();
                List<String> args = new ArrayList<>();
                for (int i = 1; i < ops.size(); i++) {
                    args.add(ops.get(i).toString());
                }

                // 如果是构造函数，需要特殊处理
                if (funcName.endsWith("_create")) {
                    String structName = funcName.replace("_create", "");
                    appendLine("__stack_top = " + runtime.generateFunctionCall(funcName, args) +
                               runtime.getStatementTerminator());
                } else {
                    appendLine("__stack_top = " + runtime.generateFunctionCall(funcName, args) +
                               runtime.getStatementTerminator());
                }
                break;
            }

            case RETURN: {
                // 返回前释放局部分配的内存
                if (!allocatedVars.isEmpty()) {
                    appendLine(runtime.generateComment("Cleanup before return"));
                    for (String var : allocatedVars) {
                        appendLine(runtime.generateDeallocation(var));
                    }
                }
                String retVal = ops.isEmpty() ? null : ops.get(0).toString();
                appendLine(runtime.generateReturn(retVal));
                break;
            }

            // ====== 三层操作流（增强版） ======
            case NORMAL_FLOW_BEGIN: {
                appendLine(runtime.generateComment("=== Normal Flow Begin ==="));
                appendLine("CLAW_TRY");
                indentLevel++;
                break;
            }

            case NORMAL_FLOW_END: {
                indentLevel = Math.max(0, indentLevel - 1);
                appendLine("CLAW_END_TRY;");
                appendLine(runtime.generateComment("=== Normal Flow End ==="));
                break;
            }

            case EXCEPTION_CATCH: {
                String exType = ops.get(0).toString();
                String varName = ops.size() > 1 ? ops.get(1).toString() : "e";
                String exEnum = "CLAW_EX_" + exType.toUpperCase();

                // 注册异常处理器
                String catchId = "catch_" + exceptionHandlers.size();
                exceptionHandlers.add(catchId);
                catchBlocks.put(catchId, varName);

                appendLine("CLAW_CATCH(" + exEnum + ")");
                indentLevel++;
                appendLine("ClawException* " + varName + " = &__claw_current_exception;");
                appendLine(runtime.generateComment("Exception handler: " + catchId));
                break;
            }

            case EXCEPTION_THROWS: {
                String exType = ops.get(0).toString();
                appendLine(runtime.generateComment("throws: " + exType));

                // 生成 throw 代码
                appendLine("ClawException ex;");
                appendLine("ex.type = CLAW_EX_" + exType.toUpperCase() + ";");
                appendLine("strcpy(ex.message, \"Exception: " + exType + "\");");
                appendLine("longjmp(__claw_jmp_buf, 1);");
                break;
            }

            case FLOW_TO: {
                // C 原生支持 goto！完美映射
                String target = ops.get(0).toString();
                appendLine(runtime.generateFlowTo(target));
                break;
            }

            // ====== 标签（flow-to 的目标） ======
            case LABEL: {
                String label = ops.get(0).toString();
                // 标签不缩进
                output.append(label).append(":");
                break;
            }

            // ====== 导入/导出 ======
            case IMPORT: {
                String module = ops.get(0).toString();
                appendLine(runtime.generateImport(module, null));
                break;
            }

            case EXPORT: {
                String symbol = ops.get(0).toString();
                appendLine(runtime.generateExport(symbol));
                break;
            }

            // ====== 类型定义（struct）（增强版） ======
            case TYPE_DEF: {
                String typeName = ops.get(0).toString();
                appendLine("");
                appendLine(runtime.generateTypeDefinitionHeader(typeName, "public"));
                indentLevel++;
                break;
            }

            case TYPE_FIELD: {
                String fieldName = ops.get(0).toString();
                String fieldType = ops.size() > 1 ? ops.get(1).toString() : "Any";
                String visibility = ops.size() > 2 ? ops.get(2).toString() : "public";

                // 记录字段信息
                allocationStack.peek().put(fieldName, fieldType);

                appendLine(runtime.generateTypeField(fieldName, fieldType, visibility));
                break;
            }

            case TYPE_END: {
                String typeName = ops.get(0).toString();
                indentLevel = Math.max(0, indentLevel - 1);
                appendLine(runtime.generateCompleteTypeDefinition(typeName));
                appendLine("");

                // 生成构造/析构辅助函数（增强版）
                appendLine(generateStructConstructor(typeName));
                appendLine(generateStructDestructor(typeName));
                appendLine(generateStructCopyFunction(typeName));
                break;
            }

            // ====== 元数据 ======
            case METADATA: {
                appendLine(runtime.generateComment("metadata: " +
                    ops.stream().map(Object::toString).collect(Collectors.joining(", "))));
                break;
            }

            // ====== NOP ======
            case NOP: {
                if (!ops.isEmpty()) {
                    appendLine(runtime.generateComment(ops.get(0).toString()));
                }
                break;
            }

            default: {
                appendLine(runtime.generateComment("Unsupported opcode: " + opCode.name()));
                break;
            }
        }
    }

    // ==================== 增强的辅助生成 ====================

    /**
     * 为 struct 生成构造函数
     */
    private String generateStructConstructor(String typeName) {
        StringBuilder sb = new StringBuilder();
        sb.append(typeName).append("* ").append(typeName).append("_create(void) {");
        sb.append("    ").append(typeName).append("* self = (")
          .append(typeName).append("*)malloc(sizeof(").append(typeName).append("));");
        sb.append("    check_allocation(self, \"").append(typeName).append("\");");
        sb.append("    memset(self, 0, sizeof(").append(typeName).append("));");

        // 初始化所有指针字段为 NULL
        sb.append("    // Initialize pointer fields to NULL");
        sb.append("    // Additional initialization code here");

        sb.append("    return self;");
        sb.append("}");
        return sb.toString();
    }

    /**
     * 为 struct 生成析构函数（实现 free nested allocations）
     */
    private String generateStructDestructor(String typeName) {
        StringBuilder sb = new StringBuilder();
        sb.append("void ").append(typeName).append("_destroy(").append(typeName).append("* self) {");
        sb.append("    if (self != NULL) {");
        sb.append("        // Free nested allocations - 实现嵌套内存释放");
        sb.append("        // 1. 释放动态数组");
        sb.append("        // 2. 释放字符串");
        sb.append("        // 3. 释放嵌套 struct");
        sb.append("        ");

        // 添加具体的嵌套释放逻辑
        sb.append(generateNestedDeallocationCode(typeName));

        sb.append("        free(self);");
        sb.append("    }");
        sb.append("}");
        return sb.toString();
    }

    /**
     * 生成嵌套释放代码
     */
    private String generateNestedDeallocationCode(String typeName) {
        StringBuilder sb = new StringBuilder();

        // 这里可以根据类型信息生成特定的释放代码
        // 示例：释放常见的嵌套结构
        sb.append("        // Example nested deallocation for ").append(typeName).append("\n");
        sb.append("        // Free string fields\n");
        sb.append("        if (self->name != NULL) free(self->name);\n");
        sb.append("        if (self->description != NULL) free(self->description);\n\n");

        sb.append("        // Free array fields\n");
        sb.append("        if (self->items != NULL) {\n");
        sb.append("            for (int i = 0; i < self->item_count; i++) {\n");
        sb.append("                if (self->items[i] != NULL) {\n");
        sb.append("                    free(self->items[i]);\n");
        sb.append("                }\n");
        sb.append("            }\n");
        sb.append("            free(self->items);\n");
        sb.append("        }\n\n");

        sb.append("        // Free nested struct fields\n");
        sb.append("        if (self->nested != NULL) {\n");
        sb.append("            NestedType_destroy(self->nested);\n");
        sb.append("            self->nested = NULL;\n");
        sb.append("        }\n");

        return sb.toString();
    }

    /**
     * 为 struct 生成拷贝函数
     */
    private String generateStructCopyFunction(String typeName) {
        StringBuilder sb = new StringBuilder();
        sb.append(typeName).append("* ").append(typeName).append("_copy(const ").append(typeName).append("* original) {");
        sb.append("    if (original == NULL) return NULL;");
        sb.append("    ").append(typeName).append("* copy = ").append(typeName).append("_create();");
        sb.append("    if (copy == NULL) return NULL;");

        // 深拷贝逻辑
        sb.append("    // Deep copy implementation");
        sb.append("    // Copy all fields from original to copy");

        sb.append("    return copy;");
        sb.append("}");
        return sb.toString();
    }

    /**
     * 生成完整的类型定义
     */
    private String generateCompleteTypeDefinition(String typeName, List<String> fields) {
        StringBuilder sb = new StringBuilder();
        sb.append("typedef struct ").append(typeName).append(" {\n");

        // 添加字段定义
        for (String field : fields) {
            sb.append("    ").append(field).append(";\n");
        }

        sb.append("} ").append(typeName).append(";");
        return sb.toString();
    }

    // ==================== 辅助方法 ====================

    /**
     * 获取当前作用域名称
     */
    private String getCurrentScope() {
        return "scope_" + (allocationStack.size() - 1);
    }

    /**
     * 判断是否为嵌套分配
     */
    private boolean isNestedAllocation(String typeName) {
        // 检查类型是否包含指针或数组
        return typeName.contains("*") || typeName.contains("[]") ||
               typeName.contains("String") || typeName.contains("List") ||
               typeName.contains("Array");
    }

    /**
     * 判断是否为基本类型（不需要 malloc/free）
     */
    private boolean isBasicType(String typeName) {
        switch (typeName) {
            case "Int": case "Float": case "Bool": case "Void":
            case "int": case "float": case "bool": case "void":
                return true;
            default:
                return false;
        }
    }

    private void appendLine(String line) {
        if (line == null || line.isEmpty()) {
            output.append("\n");
            return;
        }
        // 多行内容处理
        if (line.contains("\n")) {
            for (String subLine : line.split("\n", -1)) {
                if (!subLine.isEmpty()) {
                    String indent = "    ".repeat(Math.max(0, indentLevel));
                    output.append(indent).append(subLine).append("\n");
                } else {
                    output.append("\n");
                }
            }
            return;
        }
        String indent = "    ".repeat(Math.max(0, indentLevel));
        output.append(indent).append(line).append("\n");
    }

    private String opCodeToOperator(OpCode opCode) {
        switch (opCode) {
            case ADD: return "+";
            case SUB: return "-";
            case MUL: return "*";
            case DIV: return "/";
            case MOD: return "%";
            case CMP_EQ: return "==";
            case CMP_NE: return "!=";
            case CMP_LT: return "<";
            case CMP_GT: return ">";
            case CMP_LE: return "<=";
            case CMP_GE: return ">=";
            default: return "?";
        }
    }
}