package claw.compiler.binding.python;

import claw.compiler.binding.TargetCodeGenerator;
import claw.compiler.binding.TargetRuntime;
import claw.compiler.generators.ClawIR;
import claw.compiler.generators.IRGenerator;
import claw.compiler.generators.IRGenerator.IRBasicBlock;
import claw.compiler.generators.IRGenerator.IRInstruction;
import claw.compiler.generators.IRGenerator.OpCode;
import claw.compiler.generators.IRGenerator.OpCode.*;

import java.util.*;
import java.util.stream.Collectors;

import com.claw.binding.GenerationConfig;
import com.claw.binding.GenerationResult;

/**
 * Python 目标语言代码生成器
 * 
 * 遍历 ClawIR 中的所有指令，调用 PythonRuntime 方法生成 Python 3 代码。
 * 
 * 关键差异点（与JavaCodeGenerator相比）：
 *   1. 缩进代替花括号
 *   2. 无语句终止符（无分号）
 *   3. 逻辑运算符映射（&& -> and, || -> or, ! -> not）
 *   4. 异常处理语法（try/except 而非 try/catch）
 *   5. 类型注解而非类型声明
 *   6. 私有成员用下划线前缀约定
 */
public class PythonCodeGenerator implements TargetCodeGenerator {

    private final PythonRuntime runtime;
    private StringBuilder output;
    private int indentLevel;
    private List<String> currentFuncParams;  // 当前函数的参数列表
    private String stackTopVar;  // 当前栈顶变量名

    public PythonCodeGenerator() {
        this.runtime = new PythonRuntime();
    }

    @Override
    public TargetRuntime getRuntime() {
        return runtime;
    }

    @Override
    public String getLanguageName() {
        return "Python";
    }

    @Override
    public String getFileExtension() {
        return ".py";
    }

    @Override
    public String generate(ClawIR ir) {
        output = new StringBuilder();
        indentLevel = 0;

        // 1. 文件头注释
        appendLine("#!/usr/bin/env python3");
        appendLine(runtime.generateComment("Auto-generated by Claw Compiler"));
        appendLine(runtime.generateComment("Target: Python 3.10+"));
        appendLine(runtime.generateComment("Source: " + ir.getIrProgram().getSourceFileName()));
        appendLine("");

        // 2. 必要的 import
        for (String imp : runtime.getRequiredImports()) {
            appendLine(imp);
        }
        appendLine("");

        // 3. 运行时辅助代码
        appendLine(runtime.generateRuntimeHelpers());
        appendLine("");

        // 4. 元数据（系统注解 @@description 等，生成为模块级 docstring）
        Map metadata = ir.getIrProgram().getMetadata();
        if (metadata != null && !metadata.isEmpty()) {
            appendLine(runtime.generateDocComment((Map<String,String>)metadata));
            appendLine("");
        }

        // 5. 遍历所有顶层IR块，生成代码
        IRGenerator.IRProgram program = ir.getIrProgram();
        for (IRBasicBlock topBlock : program.getTopLevelBlocks()) {
            generateBlock(topBlock);
        }

        // 6. __main__ 入口
        appendLine("");
        appendLine("if __name__ == \"__main__\":");
        indentLevel++;
        appendLine("pass  # Entry point");
        indentLevel--;

        return output.toString();
    }

    // ==================== 块遍历 ====================

    private void generateBlock(IRBasicBlock block) {
        // 先处理当前块的所有指令
        for (IRInstruction inst : block.getInstructions()) {
            generateInstruction(inst);
        }

        // 递归处理子块
        if (block.getChildren() != null) {
            for (IRBasicBlock child : block.getChildren()) {
                generateBlock(child);
            }
        }
    }

    // ==================== 指令分派 ====================

    private void generateInstruction(IRInstruction inst) {
        OpCode opCode = inst.getOpCode();
        List<Object> ops = inst.getOperands();

        switch (opCode) {
            case WHILE_LOOP: {
                String label = ops.get(0).toString();

                // TODO: 从 IR 中提取循环条件
                // 这里暂时生成简单的 while True 循环
                appendLine("while True:  # TODO: extract condition from IR");
                appendLine("    if not __condition:  # TODO: set condition");
                appendLine("        break");
                indentLevel++;
                break;
            }

            case FOR_LOOP: {
                String varName = ops.get(0).toString();
                String iterable = ops.size() > 1 ? ops.get(1).toString() : "__iterable";
                appendLine("for " + varName + " in " + iterable + ":");
                appendLine("    pass  # loop body");
                indentLevel++;
                break;
            }

            case BREAK_LOOP: {
                appendLine(runtime.generateBreak());
                break;
            }

            case CONTINUE_LOOP: {
                appendLine(runtime.generateContinue());
                break;
            }

            case TRY_BLOCK: {
                appendLine("try:");
                indentLevel++;
                // TODO: 生成 try 代码体
                // 需要从 IR 中提取 try 代码块
                appendLine("    pass  # try block body");
                indentLevel--;
                break;
            }

            case FINALLY: {
                appendLine("finally:");
                indentLevel++;
                // TODO: 生成 finally 代码体
                appendLine("    pass  # finally block body");
                indentLevel--;
                break;
            }

            case MULTI_EXCEPTION_CATCH: {
                // 解析多个异常类型
                List<String> exTypes = new ArrayList<>();
                for (int i = 0; i < ops.size(); i++) {
                    exTypes.add(ops.get(i).toString());
                }

                // 确定变量名和处理器体
                String varName = "e";
                String handlerBody = "pass  # handle exception";
                if (exTypes.size() > 0) {
                    varName = ops.get(exTypes.size()).toString();
                }
                if (exTypes.size() > 1) {
                    handlerBody = ops.get(exTypes.size() + 1).toString();
                }

                // 映射异常类型到 Python 类型
                String pyTypes = exTypes.stream()
                    .map(op -> runtime.mapType(op.toString()))
                    .collect(Collectors.joining(", "));
                appendLine("except (" + pyTypes + ") as " + varName + ":");
                appendLine("    " + handlerBody);
                break;
            }            

            // ====== 函数定义 ======
            case FUNC_DEF: {
                String funcName = ops.get(0).toString();
                appendLine("");

                // 重置当前函数参数列表
                currentFuncParams = null;

                // 函数名转换：private 函数用下划线前缀
                String pyFuncName = "private".equals(funcName) ? "_private" : funcName;

                // 生成装饰器（如果有属性监听）
                List<String> beforeProps = new ArrayList<>();
                List<String> afterProps = new ArrayList<>();

                // TODO: 从 IR 中提取属性列表
                // 这里暂时假设所有函数都有完整的属性监听

                // 生成装饰器
                if (!beforeProps.isEmpty()) {
                    appendLine("@BeforeProps(" + String.join(", ", beforeProps) + ")");
                }
                if (!afterProps.isEmpty()) {
                    appendLine("@AfterProps(" + String.join(", ", afterProps) + ")");
                }

                // 生成 def 语句
                appendLine("def " + pyFuncName + "():");

                // 增加缩进表示函数体开始
                indentLevel++;

                // 如果有注释，添加到下一行
                if (inst.getComment() != null) {
                    appendLine(runtime.generateComment(inst.getComment()));
                }

                appendLine("    pass  # Function body");
                break;
            }

            case FUNC_END: {
                appendLine("");
                // 函数结束，减少缩进
                indentLevel = Math.max(0, indentLevel - 1);
                // 清空当前函数参数列表
                currentFuncParams = null;
                break;
            }

            // ====== 内存管理 ======
            case ALLOC: {
                String varName = ops.get(0).toString();
                String typeName = ops.size() > 1 ? ops.get(1).toString() : "Any";
                String pyType = runtime.mapType(typeName);
                // Python 不需要显式分配，只声明带类型注解的变量
                appendLine(varName + ": " + pyType + " = " + runtime.generateAllocation(typeName, null));
                break;
            }

            case DEALLOC: {
                String varName = ops.get(0).toString();
                appendLine(runtime.generateDeallocation(varName));
                break;
            }

            // ====== 变量操作 ======
            case STORE_VAR: {
                String varName = ops.get(0).toString();
                appendLine(varName + " = " + getStackTopVariable());
                if (inst.getComment() != null) {
                    // 在同一行追加注释
                    replaceLastLineComment(inst.getComment());
                }
                break;
            }

            case LOAD_VAR: {
                String varName = ops.get(0).toString();
                updateStackTopVariable("__stack_top");
                appendLine("__stack_top = " + varName);
                break;
            }

            case LOAD_CONST: {
                String value = ops.get(0).toString();
                updateStackTopVariable("__stack_top");
                appendLine("__stack_top = " + value);
                break;
            }

            // ====== 运算 ======
            case ADD: case SUB: case MUL: case DIV: case MOD: {
                String op = opCodeToOperator(opCode);
                String pyOp = mapOperatorForPython(op);
                appendLine("__stack_top = __left " + pyOp + " __right");
                break;
            }

            case CMP_EQ: case CMP_NE: case CMP_LT: case CMP_GT:
            case CMP_LE: case CMP_GE: {
                String op = opCodeToOperator(opCode);
                appendLine("__stack_top = __left " + op + " __right");
                break;
            }

            case AND: {
                appendLine("__stack_top = __left and __right");
                break;
            }

            case OR: {
                appendLine("__stack_top = __left or __right");
                break;
            }

            case NOT: {
                appendLine("__stack_top = not __operand");
                break;
            }

            // ====== 作用域 ======
            case SCOPE_ENTER: {
                String scopeName = ops.get(0).toString();
                // 生成注释标记作用域开始（保留作为文档）
                appendLine(runtime.generateComment("=== Scope: " + scopeName + " ==="));
                // 实际缩进由后续代码决定
                indentLevel++;
                break;
            }

            case SCOPE_EXIT: {
                String scopeName = ops.get(0).toString();
                // 生成注释标记作用域结束
                appendLine(runtime.generateComment("=== Exit scope: " + scopeName + " ==="));
                // 减少缩进
                indentLevel = Math.max(0, indentLevel - 1);
                break;
            }

            // ====== 控制流 ======
            case JUMP: {
                String label = ops.get(0).toString();
                appendLine(runtime.generateFlowTo(label));
                break;
            }

            case JUMP_IF_TRUE: {
                String label = ops.get(0).toString();
                appendLine(runtime.generateIf("__condition"));
                indentLevel++;
                break;
            }

            case JUMP_IF_FALSE: {
                String label = ops.get(0).toString();
                appendLine(runtime.generateIf("not __condition"));
                indentLevel++;
                break;
            }

            // ====== 属性监听钩子 ======
            case BEFORE_PROPS_HOOK: {
                String prop = ops.get(0).toString();
                appendLine(runtime.generateBeforePropsHook(prop, "__new_value"));
                if (inst.getComment() != null) {
                    replaceLastLineComment(inst.getComment());
                }
                break;
            }

            case AFTER_PROPS_HOOK: {
                String prop = ops.get(0).toString();
                appendLine(runtime.generateAfterPropsHook(prop, "__old_value", "__new_value"));
                break;
            }

            case BEFORE_NAME_HOOK: {
                String methodName = ops.get(0).toString();
                String target = ops.size() > 1 ? ops.get(1).toString() : "self";
                appendLine(runtime.generateConstructorHook(methodName, target));
                break;
            }

            case AFTER_NAME_HOOK: {
                String methodName = ops.get(0).toString();
                String target = ops.size() > 1 ? ops.get(1).toString() : "self";
                appendLine(runtime.generateDestructorHook(methodName, target));
                break;
            }

            // ====== 属性读写 ======
            case PROP_SET: {
                String prop = ops.get(0).toString();
                appendLine(prop + " = __new_value");
                break;
            }

            // ====== 数组 ======
            case ARRAY_NEW: {
                String elemType = ops.get(0).toString();
                String size = ops.size() > 1 ? ops.get(1).toString() : "0";
                appendLine("__stack_top = " + runtime.generateArrayCreation(elemType, size));
                break;
            }

            case ARRAY_GET: {
                String arrName = ops.get(0).toString();
                String index = ops.size() > 1 ? ops.get(1).toString() : "0";
                // 增加边界检查
                appendLine("if 0 <= " + index + " < len(" + arrName + "):");
                appendLine("    __stack_top = " + runtime.generateArrayGet(arrName, index));
                appendLine("else:");
                appendLine("    raise IndexError('Array index out of bounds')");
                break;
            }

            case ARRAY_SET: {
                String arrName = ops.get(0).toString();
                String index = ops.size() > 1 ? ops.get(1).toString() : "0";
                String value = ops.size() > 2 ? ops.get(2).toString() : "__stack_top";
                // 增加边界检查
                appendLine("if 0 <= " + index + " < len(" + arrName + "):");
                appendLine("    " + runtime.generateArraySet(arrName, index, value));
                appendLine("else:");
                appendLine("    raise IndexError('Array index out of bounds')");
                break;
            }

            // ====== 函数调用 ======
            case FUNC_CALL: {
                String funcName = ops.get(0).toString();
                List<String> args = new ArrayList<>();
                for (int i = 1; i < ops.size(); i++) {
                    args.add(ops.get(i).toString());
                }

                // 生成函数调用
                String call = runtime.generateFunctionCall(funcName, args);

                // 如果有返回值需要使用，生成赋值
                String resultVar = getStackTopVariable();
                if (resultVar != null) {
                    appendLine(resultVar + " = " + call);
                } else {
                    appendLine(call);
                }

                break;
            }

            case RETURN: {
                String retVal = ops.isEmpty() ? null : ops.get(0).toString();
                appendLine(runtime.generateReturn(retVal));
                break;
            }

            // ====== 三层操作流 ======
            case NORMAL_FLOW_BEGIN: {
                appendLine(runtime.generateComment("=== Normal Flow Begin ==="));
                break;
            }

            case NORMAL_FLOW_END: {
                appendLine(runtime.generateComment("=== Normal Flow End ==="));
                break;
            }

            case EXCEPTION_CATCH: {
                String exType = ops.get(0).toString();
                String varName = ops.size() > 1 ? ops.get(1).toString() : "e";
                appendLine(runtime.generateCatchBlock(exType, varName, "pass  # handle exception"));
                break;
            }

            case EXCEPTION_THROWS: {
                String exType = ops.get(0).toString();
                appendLine(runtime.generateComment("Raises: " + runtime.mapType(exType)));
                break;
            }

            case LABEL: {
                String labelName = ops.get(0).toString();
                appendLine(labelName + ":");
                break;
            }

            // ====== 导入/导出 ======
            case IMPORT: {
                String module = ops.get(0).toString();
                String symbol = ops.size() > 1 ? ops.get(1).toString() : null;
                appendLine(runtime.generateImport(module, symbol));
                break;
            }

            case EXPORT: {
                String symbol = ops.get(0).toString();
                appendLine(runtime.generateExport(symbol));
                break;
            }

            // ====== 类型定义 ======
            case TYPE_DEF: {
                String typeName = ops.get(0).toString();
                appendLine("");

                // 生成类定义头
                appendLine(runtime.generateTypeDefinitionHeader(typeName, "public"));

                // 增加缩进表示类体开始
                indentLevel++;

                // 如果有注释，添加到下一行
                if (inst.getComment() != null) {
                    appendLine(runtime.generateComment(inst.getComment()));
                }

                appendLine("    pass  # Type definition");
                break;
            }

            // ====== 元数据 ======
            case METADATA: {
                appendLine(runtime.generateComment("metadata: " +
                    ops.stream().map(Object::toString).collect(Collectors.joining(", "))));
                break;
            }

            // ====== NOP ======
            case NOP: {
                if (!ops.isEmpty()) {
                    appendLine(runtime.generateComment(ops.get(0).toString()));
                } else {
                    appendLine("pass");
                }
                break;
            }

            default: {
                appendLine(runtime.generateComment("TODO: " + opCode.name()));
                break;
            }
        }
    }

    // ==================== 辅助方法 ====================

    private String getFieldName(String propertyPath) {
        // 从 propertyPath 中提取字段名
        // 例如: "user.address.city" → "address.city"
        int lastDot = propertyPath.lastIndexOf('.');
        return lastDot > 0 ? propertyPath.substring(lastDot + 1) : propertyPath;
    }

    private String getStackTopVariable() {
        return "__stack_top";
    }

    private void updateStackTopVariable(String newVar) {
        this.stackTopVar = newVar;
    }

    private void appendLine(String line) {
        if (line == null || line.isEmpty()) {
            output.append("\n");
            return;
        }
        // 处理多行内容（如 generateRuntimeHelpers 返回的多行字符串）
        if (line.contains("\n")) {
            for (String subLine : line.split("\n", -1)) {
                if (!subLine.isEmpty()) {
                    String indent = "    ".repeat(Math.max(0, indentLevel));
                    output.append(indent).append(subLine).append("\n");
                } else {
                    output.append("");
                }
            }
            return;
        }
        String indent = "    ".repeat(Math.max(0, indentLevel));
        output.append(indent).append(line).append("\n");
    }

    /**
     * 在最后一行末尾追加注释
     */
    private void replaceLastLineComment(String comment) {
        int lastNewline = output.lastIndexOf("\n", output.length() - 2);
        if (lastNewline >= 0) {
            // 在最后一行的换行符前插入注释
            output.insert(output.length() - 1, "  " + runtime.generateComment(comment));
        }
    }

    private String opCodeToOperator(OpCode opCode) {
        switch (opCode) {
            case ADD: return "+";
            case SUB: return "-";
            case MUL: return "*";
            case DIV: return "/";
            case MOD: return "%";
            case CMP_EQ: return "==";
            case CMP_NE: return "!=";
            case CMP_LT: return "<";
            case CMP_GT: return ">";
            case CMP_LE: return "<=";
            case CMP_GE: return ">=";
            default: return "?";
        }
    }

    private String mapOperatorForPython(String op) {
        switch (op) {
            case "&&": return "and";
            case "||": return "or";
            case "!":  return "not";
            default:   return op;
        }
    }

    @Override
    public GenerationResult generate(com.claw.ir.ClawIR ir, GenerationConfig defaultConfig) {
        GenerationResult result = new GenerationResult();
        if (ir == null) {
            result.addWarning("No IR provided for Python code generation.");
            return result;
        }
        String fileName = "claw_output" + getFileExtension();
        result.addFile(fileName, "# Python code generation not supported for com.claw.ir.ClawIR yet\n");
        return result;
    }
}
