"""
编译器生成的 Python 代码（同一份 Claw 源码，不同目标）
Python 目标使用 ctypes 调用 C 库：
Auto-generated by Claw Compiler
Source: database_example.claw
Target: Python 3.10+
"""

import ctypes
import ctypes.util
import claw_runtime

# ========== Load C Library ==========
_lib_path = ctypes.util.find_library("sqlite3")
if _lib_path is None:
    raise claw_runtime.ClawIOError("Cannot find library: sqlite3")
_sqlite3 = ctypes.CDLL(_lib_path)

# ========== Constants ==========
SQLITE_OK = 0
SQLITE_ROW = 100
SQLITE_DONE = 101

# ========== C Function Signatures ==========
_sqlite3.sqlite3_open.argtypes = [ctypes.c_char_p, ctypes.POINTER(ctypes.c_void_p)]
_sqlite3.sqlite3_open.restype = ctypes.c_int

_sqlite3.sqlite3_close.argtypes = [ctypes.c_void_p]
_sqlite3.sqlite3_close.restype = ctypes.c_int

_sqlite3.sqlite3_errmsg.argtypes = [ctypes.c_void_p]
_sqlite3.sqlite3_errmsg.restype = ctypes.c_char_p

_sqlite3.sqlite3_exec.argtypes = [
    ctypes.c_void_p, ctypes.c_char_p,
    ctypes.c_void_p, ctypes.c_void_p,
    ctypes.POINTER(ctypes.c_char_p)
]
_sqlite3.sqlite3_exec.restype = ctypes.c_int

_sqlite3.sqlite3_prepare_v2.argtypes = [
    ctypes.c_void_p, ctypes.c_char_p, ctypes.c_int,
    ctypes.POINTER(ctypes.c_void_p), ctypes.c_void_p
]
_sqlite3.sqlite3_prepare_v2.restype = ctypes.c_int

_sqlite3.sqlite3_step.argtypes = [ctypes.c_void_p]
_sqlite3.sqlite3_step.restype = ctypes.c_int

_sqlite3.sqlite3_finalize.argtypes = [ctypes.c_void_p]
_sqlite3.sqlite3_finalize.restype = ctypes.c_int

_sqlite3.sqlite3_column_text.argtypes = [ctypes.c_void_p, ctypes.c_int]
_sqlite3.sqlite3_column_text.restype = ctypes.c_char_p

_sqlite3.sqlite3_column_int.argtypes = [ctypes.c_void_p, ctypes.c_int]
_sqlite3.sqlite3_column_int.restype = ctypes.c_int


# ========== Type: Database ==========
class Database:
    def __init__(self):
        self.handle = ctypes.c_void_p(None)
        self.isOpen = False


# ========== Functions ==========

def openDatabase(path: str) -> Database:
    db = Database()
    try:
        handle = ctypes.c_void_p()
        result = _sqlite3.sqlite3_open(path.encode('utf-8'), ctypes.byref(handle))
        if result != SQLITE_OK:
            msg = _sqlite3.sqlite3_errmsg(handle)
            raise claw_runtime.ClawIOError(
                "Cannot open database: " + (msg.decode('utf-8') if msg else "unknown")
            )
        db.handle = handle
        db.isOpen = True
        return db
    except claw_runtime.ClawIOError as e:
        print("Database error: " + e.message)
        raise


def query(db: Database, sql: str) -> None:
    stmt = ctypes.c_void_p(None)
    try:
        rc = _sqlite3.sqlite3_prepare_v2(
            db.handle, sql.encode('utf-8'), -1,
            ctypes.byref(stmt), None
        )
        if rc != SQLITE_OK:
            msg = _sqlite3.sqlite3_errmsg(db.handle)
            raise claw_runtime.ClawIOError(
                "SQL prepare failed: " + (msg.decode('utf-8') if msg else "unknown")
            )

        while _sqlite3.sqlite3_step(stmt) == SQLITE_ROW:
            name = _sqlite3.sqlite3_column_text(stmt, 0)
            age = _sqlite3.sqlite3_column_int(stmt, 1)
            name_str = name.decode('utf-8') if name else ""
            print(f"{name_str}: {age}")

        _sqlite3.sqlite3_finalize(stmt)

    except claw_runtime.ClawIOError as e:
        if stmt:
            _sqlite3.sqlite3_finalize(stmt)
        print("Query error: " + e.message)


def closeDatabase(db: Database) -> None:
    if db.isOpen:
        _sqlite3.sqlite3_close(db.handle)
        db.isOpen = False


# ========== Main ==========
if __name__ == "__main__":
    db = openDatabase("users.db")
    query(db, "SELECT name, age FROM users")
    closeDatabase(db)
