/**
 * Auto-generated by Claw Compiler
 * Source: database_example.claw
 * Target: C11
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "claw_runtime.h"

/* extern "C" { include "sqlite3.h" } */
#include <sqlite3.h>

/* ========== Type: Database ========== */
typedef struct Database {
    sqlite3* handle;
    bool     isOpen;
} Database;

/* ========== Functions ========== */

Database openDatabase(const char* path) {
    Database db;
    memset(&db, 0, sizeof(Database));

    CLAW_TRY

        int result = sqlite3_open(path, &db.handle);
        if (result != SQLITE_OK) {
            char msg_buf[512];
            snprintf(msg_buf, sizeof(msg_buf),
                "Cannot open database: %s", sqlite3_errmsg(db.handle));
            __claw_throw(CLAW_EX_IOERROR, msg_buf);
        }

        db.isOpen = true;
        return db;

    CLAW_CATCH(CLAW_EX_IOERROR)
        ClawException* e = &__claw_current_exception;
        printf("Database error: %s", e->message);
        /* re-throw */
        __claw_throw(CLAW_EX_IOERROR, e->message);

    CLAW_END_TRY;

    return db;
}

void query(Database db, const char* sql) {
    sqlite3_stmt* stmt = NULL;

    CLAW_TRY

        int rc = sqlite3_prepare_v2(db.handle, sql, -1, &stmt, NULL);
        if (rc != SQLITE_OK) {
            char msg_buf[512];
            snprintf(msg_buf, sizeof(msg_buf),
                "SQL prepare failed: %s", sqlite3_errmsg(db.handle));
            __claw_throw(CLAW_EX_IOERROR, msg_buf);
        }

        while (sqlite3_step(stmt) == SQLITE_ROW) {
            const char* name = (const char*)sqlite3_column_text(stmt, 0);
            int age = sqlite3_column_int(stmt, 1);
            printf("%s: %d", name, age);
        }

        sqlite3_finalize(stmt);

    CLAW_CATCH(CLAW_EX_IOERROR)
        ClawException* e = &__claw_current_exception;
        if (stmt != NULL) {
            sqlite3_finalize(stmt);
        }
        printf("Query error: %s", e->message);

    CLAW_END_TRY;
}

void closeDatabase(Database* db) {
    if (db->isOpen) {
        sqlite3_close(db->handle);
        db->isOpen = false;
    }
}

int main(int argc, char* argv[]) {
    Database db = openDatabase("users.db");
    query(db, "SELECT name, age FROM users");
    closeDatabase(&db);
    return 0;
}
