// // ==================== CodeGenerator.java ====================
// package com.claw.compiler.generators;

// import com.claw.compiler.annotation.AnnotationManager;
// import com.claw.compiler.annotation.ProgramAnnotation;
// import com.claw.compiler.annotation.SystemAnnotation;
// import com.claw.compiler.flow.FlowManager;
// import com.claw.compiler.frontend.ASTNode;
// import com.claw.compiler.pipeline.GeneratedCode;
// import lombok.extern.slf4j.Slf4j;

// import java.util.*;

// /**
//  * 代码生成器 - 第4层验证生成处理器
//  *
//  * 实现思想2的最后一步：从最底层代码块开始生成
//  * 1. 生成伪代码
//  * 2. 生成中间表示
//  * 3. 生成最终目标代码
//  */
// @Slf4j
// public class CodeGenerator {

//     private final StringBuilder targetCode = new StringBuilder();
//     private final StringBuilder pseudoCode = new StringBuilder();
//     private final StringBuilder irCode = new StringBuilder();
//     private int indentLevel = 0;

//     /**
//      * 生成代码
//      */
//     public GeneratedCode generate(ASTNode ast, AnnotationManager annotationManager,
//                                    FlowManager flowManager) {
//         log.info("开始代码生成...");

//         targetCode.setLength(0);
//         pseudoCode.setLength(0);
//         irCode.setLength(0);
//         indentLevel = 0;

//         // 生成文件头部
//         generateHeader(annotationManager);

//         // 生成主体代码
//         generateNode(ast, flowManager);

//         // 收集元数据
//         Map<String, String> metadata = collectMetadata(annotationManager);

//         int funcCount = countNodes(ast, ASTNode.NodeType.FUNCTION_DECLARATION);
//         int typeCount = countNodes(ast, ASTNode.NodeType.TYPE_DEFINITION);

//         GeneratedCode code = GeneratedCode.builder()
//                 .targetCode(targetCode.toString())
//                 .intermediateRepresentation(irCode.toString())
//                 .pseudoCode(pseudoCode.toString())
//                 .metadata(metadata)
//                 .sourceFileName(ast.getProperty("fileName"))
//                 .functionCount(funcCount)
//                 .typeCount(typeCount)
//                 .build();

//         log.info("代码生成完成: {} 个函数, {} 个类型, {} 字符",
//                 funcCount, typeCount, targetCode.length());

//         return code;
//     }

//     /**
//      * 生成文件头部（包含系统注解元数据）
//      */
//     private void generateHeader(AnnotationManager annotationManager) {
//         targetCode.append("// Generated by Claw Compiler v3.0
// ");
//         targetCode.append("// Date: ").append(new Date()).append("
// ");

//         if (annotationManager != null) {
//             List<SystemAnnotation> sysAnnotations = annotationManager.getSystemAnnotations();
//             if (!sysAnnotations.isEmpty()) {
//                 targetCode.append("
// // === System Annotations ===
// ");
//                 for (SystemAnnotation ann : sysAnnotations) {
//                     targetCode.append("// @@").append(ann.getType())
//                              .append(": ").append(ann.getValue()).append("
// ");
//                 }
//                 targetCode.append("
// ");
//             }
//         }

//         irCode.append("; Claw IR v3.0
// ");
//         irCode.append("; Module: main

// ");

//         pseudoCode.append("# Claw Pseudo Code

// ");
//     }

//     /**
//      * 递归生成AST节点代码
//      */
//     private void generateNode(ASTNode node, FlowManager flowManager) {
//         if (node == null) return;

//         switch (node.getType()) {
//             case PROGRAM -> generateProgram(node, flowManager);
//             case IMPORT_DECLARATION -> generateImport(node);
//             case TYPE_DEFINITION -> generateTypeDefinition(node, flowManager);
//             case FUNCTION_DECLARATION -> generateFunction(node, flowManager);
//             case VARIABLE_DECLARATION -> generateVariableDeclaration(node, flowManager);
//             case ASSIGNMENT -> generateAssignment(node, flowManager);
//             case IF_STATEMENT -> generateIfStatement(node, flowManager);
//             case FOR_STATEMENT -> generateForStatement(node, flowManager);
//             case WHILE_STATEMENT -> generateWhileStatement(node, flowManager);
//             case RETURN_STATEMENT -> generateReturnStatement(node, flowManager);
//             case FUNCTION_CALL -> generateFunctionCall(node, flowManager);
//             case BINARY_EXPRESSION -> generateBinaryExpression(node, flowManager);
//             case BLOCK -> generateBlock(node, flowManager);
//             case CATCH_CLAUSE -> generateCatchClause(node, flowManager);
//             case FLOW_STATEMENT -> generateFlowStatement(node);
//             default -> {
//                 for (ASTNode child : node.getChildren()) {
//                     generateNode(child, flowManager);
//                 }
//             }
//         }
//     }

//     private void generateProgram(ASTNode node, FlowManager flowManager) {
//         for (ASTNode child : node.getChildren()) {
//             generateNode(child, flowManager);
//         }
//     }

//     private void generateImport(ASTNode node) {
//         String module = node.getProperty("module");
//         String items = node.getProperty("items");

//         indent();
//         targetCode.append("import ").append(module);
//         if (items != null) {
//             targetCode.append(" { ").append(items).append(" }");
//         }
//         targetCode.append(";
// ");

//         irCode.append("import @").append(module).append("
// ");
//         pseudoCode.append("导入 ").append(module).append("
// ");
//     }

//     private void generateTypeDefinition(ASTNode node, FlowManager flowManager) {
//         String typeName = node.getProperty("name");

//         indent();
//         targetCode.append("class ").append(typeName).append(" {
// ");
//         irCode.append("define type @").append(typeName).append(" {
// ");
//         pseudoCode.append("定义类型 ").append(typeName).append(":
// ");

//         indentLevel++;

//         for (ASTNode child : node.getChildren()) {
//             if (child.getType() == ASTNode.NodeType.VARIABLE_DECLARATION) {
//                 // 字段声明
//                 String fieldName = child.getProperty("name");
//                 String fieldType = child.getProperty("varType");
//                 if (fieldType == null) fieldType = "Any";

//                 indent();
//                 targetCode.append(fieldType).append(" ").append(fieldName).append(";
// ");

//                 irCode.append("  field ").append(fieldType).append(" %")
//                       .append(fieldName).append("
// ");

//                 pseudoCode.append("  字段 ").append(fieldName)
//                           .append(" : ").append(fieldType).append("
// ");

//             } else if (child.getType() == ASTNode.NodeType.FUNCTION_DECLARATION) {
//                 generateFunction(child, flowManager);
//             }
//         }

//         indentLevel--;
//         indent();
//         targetCode.append("}

// ");
//         irCode.append("}

// ");
//         pseudoCode.append("
// ");
//     }

//     private void generateFunction(ASTNode node, FlowManager flowManager) {
//         String funcName = node.getProperty("name");
//         String returnType = node.getProperty("returnType");
//         String flowType = node.getProperty("flowType");
//         String visibility = node.getProperty("visibility");
//         if (returnType == null) returnType = "Void";
//         if (visibility == null) visibility = "public";

//         // 目标代码
//         indent();
//         if (visibility != null) {
//             targetCode.append(visibility).append(" ");
//         }
//         targetCode.append(returnType).append(" ").append(funcName).append("(");

//         // 中间表示
//         irCode.append("define ").append(returnType).append(" @").append(funcName).append("(");

//         // 伪代码
//         pseudoCode.append("函数 ").append(funcName).append("(");

//         // 参数列表
//         ASTNode params = node.getChildByType(ASTNode.NodeType.PARAMETER_LIST);
//         if (params != null) {
//             List<ASTNode> paramList = params.getChildren();
//             for (int i = 0; i < paramList.size(); i++) {
//                 ASTNode param = paramList.get(i);
//                 String paramName = param.getProperty("name");
//                 String paramType = param.getProperty("paramType");
//                 if (paramType == null) paramType = "Any";

//                 if (i > 0) {
//                     targetCode.append(", ");
//                     irCode.append(", ");
//                     pseudoCode.append(", ");
//                 }
//                 targetCode.append(paramType).append(" ").append(paramName);
//                 irCode.append(paramType).append(" %").append(paramName);
//                 pseudoCode.append(paramName).append(":").append(paramType);
//             }
//         }

//         targetCode.append(") {
// ");
//         irCode.append(") {
// ");
//         pseudoCode.append(") -> ").append(returnType).append(":
// ");

//         // 如果有操作流类型注释
//         if (flowType != null && !"normal".equals(flowType)) {
//             irCode.append("  ; flow_type: ").append(flowType).append("
// ");
//         }

//         // 函数体
//         indentLevel++;
//         ASTNode body = node.getChildByType(ASTNode.NodeType.BLOCK);
//         if (body != null) {
//             for (ASTNode child : body.getChildren()) {
//                 generateNode(child, flowManager);
//             }
//         }
//         indentLevel--;

//         indent();
//         targetCode.append("}

// ");
//         irCode.append("}

// ");
//         pseudoCode.append("
// ");
//     }

//     private void generateVariableDeclaration(ASTNode node, FlowManager flowManager) {
//         String varName = node.getProperty("name");
//         String varType = node.getProperty("varType");
//         boolean isConst = "true".equals(node.getProperty("const"));
//         if (varType == null) varType = "var";

//         indent();
//         targetCode.append(isConst ? "final " : "")
//                  .append(varType).append(" ").append(varName);

//         irCode.append("  ").append(isConst ? "const" : "alloca")
//               .append(" ").append(varType).append(" %").append(varName);

//         pseudoCode.append("  ").append(isConst ? "常量" : "变量")
//                   .append(" ").append(varName).append(" : ").append(varType);

//         // 初始化表达式
//         if (!node.getChildren().isEmpty()) {
//             targetCode.append(" = ");
//             irCode.append(" = ");
//             pseudoCode.append(" = ");

//             ASTNode init = node.getChildren().get(0);
//             generateExpression(init, flowManager);
//         }

//         targetCode.append(";
// ");
//         irCode.append("
// ");
//         pseudoCode.append("
// ");
//     }

//     private void generateAssignment(ASTNode node, FlowManager flowManager) {
//         if (node.getChildren().size() < 2) return;

//         ASTNode target = node.getChildren().get(0);
//         ASTNode value = node.getChildren().get(1);

//         indent();
//         targetCode.append(target.getValue()).append(" = ");
//         irCode.append("  store %").append(target.getValue()).append(", ");
//         pseudoCode.append("  ").append(target.getValue()).append(" = ");

//         generateExpression(value, flowManager);

//         targetCode.append(";
// ");
//         irCode.append("
// ");
//         pseudoCode.append("
// ");
//     }

//     private void generateIfStatement(ASTNode node, FlowManager flowManager) {
//         indent();
//         targetCode.append("if (");
//         irCode.append("  br ");
//         pseudoCode.append("  如果 ");

//         // 条件
//         ASTNode condition = null;
//         ASTNode thenBlock = null;
//         ASTNode elseBlock = null;

//         for (ASTNode child : node.getChildren()) {
//             if (child.getType() == ASTNode.NodeType.BLOCK) {
//                 if (thenBlock == null) {
//                     thenBlock = child;
//                 } else {
//                     elseBlock = child;
//                 }
//             } else {
//                 condition = child;
//             }
//         }

//         if (condition != null) {
//             generateExpression(condition, flowManager);
//         }

//         targetCode.append(") {
// ");
//         irCode.append(" label %then, label %else
// ");
//         pseudoCode.append(" 则:
// ");

//         // then 块
//         indentLevel++;
//         if (thenBlock != null) {
//             irCode.append("then:
// ");
//             for (ASTNode child : thenBlock.getChildren()) {
//                 generateNode(child, flowManager);
//             }
//         }
//         indentLevel--;

//         // else 块
//         if (elseBlock != null) {
//             indent();
//             targetCode.append("} else {
// ");
//             irCode.append("else:
// ");
//             pseudoCode.append("  否则:
// ");

//             indentLevel++;
//             for (ASTNode child : elseBlock.getChildren()) {
//                 generateNode(child, flowManager);
//             }
//             indentLevel--;
//         }

//         indent();
//         targetCode.append("}
// ");
//         irCode.append("endif:
// ");
//         pseudoCode.append("  结束如果
// ");
//     }

//     private void generateForStatement(ASTNode node, FlowManager flowManager) {
//         indent();
//         targetCode.append("for (");
//         irCode.append("  ; for loop
// ");
//         irCode.append("loop_start:
// ");
//         pseudoCode.append("  循环 ");

//         String iterVar = node.getProperty("iterator");
//         String range = node.getProperty("range");
//         if (iterVar != null) {
//             targetCode.append("var ").append(iterVar);
//             pseudoCode.append(iterVar);
//         }
//         if (range != null) {
//             targetCode.append(" : ").append(range);
//             pseudoCode.append(" 在 ").append(range);
//         }

//         targetCode.append(") {
// ");
//         pseudoCode.append(":
// ");

//         indentLevel++;
//         ASTNode body = node.getChildByType(ASTNode.NodeType.BLOCK);
//         if (body != null) {
//             for (ASTNode child : body.getChildren()) {
//                 generateNode(child, flowManager);
//             }
//         }
//         indentLevel--;

//         indent();
//         targetCode.append("}
// ");
//         irCode.append("  br label %loop_start
// ");
//         irCode.append("loop_end:
// ");
//         pseudoCode.append("  结束循环
// ");
//     }

//     private void generateWhileStatement(ASTNode node, FlowManager flowManager) {
//         indent();
//         targetCode.append("while (");
//         irCode.append("  ; while loop
// ");
//         irCode.append("while_start:
// ");
//         pseudoCode.append("  当 ");

//         ASTNode condition = null;
//         ASTNode body = null;
//         for (ASTNode child : node.getChildren()) {
//             if (child.getType() == ASTNode.NodeType.BLOCK) {
//                 body = child;
//             } else {
//                 condition = child;
//             }
//         }

//         if (condition != null) {
//             generateExpression(condition, flowManager);
//         }

//         targetCode.append(") {
// ");
//         pseudoCode.append(" 时:
// ");

//         indentLevel++;
//         if (body != null) {
//             for (ASTNode child : body.getChildren()) {
//                 generateNode(child, flowManager);
//             }
//         }
//         indentLevel--;

//         indent();
//         targetCode.append("}
// ");
//         irCode.append("  br label %while_start
// ");
//         irCode.append("while_end:
// ");
//         pseudoCode.append("  结束当
// ");
//     }

//     private void generateReturnStatement(ASTNode node, FlowManager flowManager) {
//         indent();
//         targetCode.append("return");
//         irCode.append("  ret ");
//         pseudoCode.append("  返回 ");

//         if (!node.getChildren().isEmpty()) {
//             targetCode.append(" ");
//             generateExpression(node.getChildren().get(0), flowManager);
//         } else {
//             irCode.append("void");
//         }

//         targetCode.append(";
// ");
//         irCode.append("
// ");
//         pseudoCode.append("
// ");
//     }

//     private void generateFunctionCall(ASTNode node, FlowManager flowManager) {
//         String funcName = node.getProperty("name");
//         if (funcName == null) funcName = node.getValue();

//         targetCode.append(funcName).append("(");
//         irCode.append("call @").append(funcName).append("(");
//         pseudoCode.append("调用 ").append(funcName).append("(");

//         ASTNode args = node.getChildByType(ASTNode.NodeType.ARGUMENT_LIST);
//         if (args != null) {
//             List<ASTNode> argList = args.getChildren();
//             for (int i = 0; i < argList.size(); i++) {
//                 if (i > 0) {
//                     targetCode.append(", ");
//                     irCode.append(", ");
//                     pseudoCode.append(", ");
//                 }
//                 generateExpression(argList.get(i), flowManager);
//             }
//         }

//         targetCode.append(")");
//         irCode.append(")");
//         pseudoCode.append(")");
//     }

//     private void generateCatchClause(ASTNode node, FlowManager flowManager) {
//         // 思想1：异常流简化 - 去掉try和{}，catch与当前代码块边界一致
//         String exceptionType = node.getProperty("exceptionType");
//         String exceptionVar = node.getProperty("exceptionVar");

//         indent();
//         targetCode.append("catch (");
//         if (exceptionType != null) targetCode.append(exceptionType).append(" ");
//         if (exceptionVar != null) targetCode.append(exceptionVar);
//         targetCode.append(") {
// ");

//         irCode.append("  ; exception handler - no stack trace (performance optimized)
// ");
//         irCode.append("catch_").append(exceptionType != null ? exceptionType : "any").append(":
// ");

//         pseudoCode.append("  捕获异常 ");
//         if (exceptionType != null) pseudoCode.append(exceptionType);
//         pseudoCode.append(":
// ");

//         indentLevel++;
//         ASTNode body = node.getChildByType(ASTNode.NodeType.BLOCK);
//         if (body != null) {
//             for (ASTNode child : body.getChildren()) {
//                 generateNode(child, flowManager);
//             }
//         }
//         indentLevel--;

//         indent();
//         targetCode.append("}
// ");
//     }

//     private void generateFlowStatement(ASTNode node) {
//         // 思想1：业务逻辑流转 - flow to target
//         String target = node.getProperty("target");

//         indent();
//         targetCode.append("/* flow */ goto ").append(target).append(";
// ");

//         irCode.append("  ; business flow - no stack recording
// ");
//         irCode.append("  br label %").append(target).append("
// ");

//         pseudoCode.append("  流转到 ").append(target).append("
// ");
//     }

//     private void generateBlock(ASTNode node, FlowManager flowManager) {
//         for (ASTNode child : node.getChildren()) {
//             generateNode(child, flowManager);
//         }
//     }

//     private void generateBinaryExpression(ASTNode node, FlowManager flowManager) {
//         if (node.getChildren().size() < 2) return;

//         ASTNode left = node.getChildren().get(0);
//         ASTNode right = node.getChildren().get(1);
//         String op = node.getProperty("operator");
//         if (op == null) op = node.getValue();

//         generateExpression(left, flowManager);
//         targetCode.append(" ").append(op).append(" ");
//         irCode.append(" ").append(mapOperatorToIR(op)).append(" ");
//         pseudoCode.append(" ").append(op).append(" ");
//         generateExpression(right, flowManager);
//     }

//     /**
//      * 生成表达式代码
//      */
//     private void generateExpression(ASTNode node, FlowManager flowManager) {
//         if (node == null) return;

//         switch (node.getType()) {
//             case LITERAL -> {
//                 String val = node.getValue();
//                 targetCode.append(val);
//                 irCode.append(val);
//                 pseudoCode.append(val);
//             }
//             case IDENTIFIER -> {
//                 String name = node.getValue();
//                 targetCode.append(name);
//                 irCode.append("%").append(name);
//                 pseudoCode.append(name);
//             }
//             case BINARY_EXPRESSION -> generateBinaryExpression(node, flowManager);
//             case FUNCTION_CALL -> generateFunctionCall(node, flowManager);
//             case UNARY_EXPRESSION -> {
//                 String op = node.getProperty("operator");
//                 targetCode.append(op);
//                 irCode.append(op);
//                 pseudoCode.append(op);
//                 if (!node.getChildren().isEmpty()) {
//                     generateExpression(node.getChildren().get(0), flowManager);
//                 }
//             }
//             default -> {
//                 String val = node.getValue();
//                 if (val != null) {
//                     targetCode.append(val);
//                     irCode.append(val);
//                     pseudoCode.append(val);
//                 }
//             }
//         }
//     }

//     /**
//      * 映射运算符到IR格式
//      */
//     private String mapOperatorToIR(String operator) {
//         return switch (operator) {
//             case "+" -> "add";
//             case "-" -> "sub";
//             case "*" -> "mul";
//             case "/" -> "div";
//             case "%" -> "mod";
//             case "==" -> "eq";
//             case "!=" -> "ne";
//             case "<" -> "lt";
//             case ">" -> "gt";
//             case "<=" -> "le";
//             case ">=" -> "ge";
//             case "&&" -> "and";
//             case "||" -> "or";
//             default -> operator;
//         };
//     }

//     /**
//      * 收集系统注解元数据
//      */
//     private Map<String, String> collectMetadata(AnnotationManager annotationManager) {
//         Map<String, String> metadata = new LinkedHashMap<>();
//         if (annotationManager == null) return metadata;

//         for (SystemAnnotation ann : annotationManager.getSystemAnnotations()) {
//             metadata.put(ann.getType(), ann.getValue());
//         }
//         return metadata;
//     }

//     /**
//      * 统计特定类型节点数量
//      */
//     private int countNodes(ASTNode node, ASTNode.NodeType type) {
//         if (node == null) return 0;
//         int count = (node.getType() == type) ? 1 : 0;
//         for (ASTNode child : node.getChildren()) {
//             count += countNodes(child, type);
//         }
//         return count;
//     }

//     /**
//      * 生成缩进
//      */
//     private void indent() {
//         targetCode.append("    ".repeat(indentLevel));
//     }
// }
