package com.q3lives.compiler.generators.ffi;

import com.q3lives.compiler.generators.ffi.FFIBindingTable.*;
import java.util.*;

/**
 * Java 目标 FFI 代码生成器（Panama 策略）
 *
 * <p>使用 Java 22+ Foreign Function & Memory API 生成类型安全的原生绑定。
 * 生成包含 MethodHandle、ValueLayout、Arena 的完整 Java 类。</p>
 */
public class JavaFFIGenerator {

    private final FFIBindingTable bindingTable;
    private final String className;

    public JavaFFIGenerator(FFIBindingTable bindingTable) {
        this(bindingTable, "ClawFFIBindings");
    }

    public JavaFFIGenerator(FFIBindingTable bindingTable, String className) {
        this.bindingTable = bindingTable;
        this.className = className;
    }

    // ================================================================
    //  完整代码生成
    // ================================================================

    /**
     * 生成完整的 Java FFI 类
     */
    public String generateAll() {
        if (!bindingTable.hasExternDeclarations()) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        sb.append(generatePackageAndImports());
        sb.append(generateClassHeader());
        sb.append(generateStructDefinitions());
        sb.append(generateEnumDefinitions());
        sb.append(generateCallbackDefinitions());
        sb.append(generateLibraryLoading());
        sb.append(generateConstants());
        sb.append(generateMethodHandles());
        sb.append(generateWrapperMethods());
        sb.append(generateHelperMethods());
        sb.append("}\n");
        return sb.toString();
    }

    // ================================================================
    //  包声明和导入
    // ================================================================

    public String generatePackageAndImports() {
        StringBuilder sb = new StringBuilder();
        sb.append("package claw.ffi;\n\n");
        sb.append("import java.lang.foreign.*;\n");
        sb.append("import java.lang.invoke.MethodHandle;\n");
        sb.append("import java.nio.charset.StandardCharsets;\n");
        sb.append("import java.util.Optional;\n\n");
        return sb.toString();
    }

    // ================================================================
    //  类头
    // ================================================================

    public String generateClassHeader() {
        StringBuilder sb = new StringBuilder();
        sb.append("/**\n");
        sb.append(" * Auto-generated FFI bindings for Claw compiler.\n");
        sb.append(" * \n");
        sb.append(" * <p>Generated by JavaFFIGenerator (Panama strategy).\n");
        sb.append(" * Requires Java 22+.</p>\n");
        sb.append(" */\n");
        sb.append("public final class ").append(className).append(" {\n\n");
        return sb.toString();
    }

    // ================================================================
    //  库加载
    // ================================================================

    /**
     * 生成静态初始化代码：加载共享库和查找符号
     */
    public String generateLibraryLoading() {
        List<String> libNames = bindingTable.getLibraryNames();
        if (libNames.isEmpty()) return "";

        StringBuilder sb = new StringBuilder();
        sb.append("    private static final Linker LINKER = Linker.nativeLinker();\n");

        for (String libName : libNames) {
            String varName = toSafeJavaName(libName).toUpperCase() + "_LOOKUP";
            sb.append("    private static final SymbolLookup ").append(varName).append(";\n");
        }

        sb.append("\n    static {\n");
        for (String libName : libNames) {
            String varName = toSafeJavaName(libName).toUpperCase() + "_LOOKUP";
            sb.append("        ").append(varName).append(" = SymbolLookup.libraryLookup(\n");
            sb.append("            System.mapLibraryName(\"").append(libName).append("\"),\n");
            sb.append("            Arena.global()\n");
            sb.append("        );\n");
        }
        sb.append("    }\n\n");
        return sb.toString();
    }

    // ================================================================
    //  常量定义
    // ================================================================

    public String generateConstants() {
        Map<String, ExternConstant> constants = bindingTable.getAllConstants();
        if (constants.isEmpty()) return "";

        StringBuilder sb = new StringBuilder();
        sb.append("    /* ========== Constants ========== */\n");
        for (ExternConstant constant : constants.values()) {
            String javaType = mapToJavaConstantType(constant.type);
            sb.append("    public static final ").append(javaType)
              .append(" ").append(constant.name).append(" = ")
              .append(constant.value).append(";\n");
        }
        sb.append("\n");
        return sb.toString();
    }

    // ================================================================
    //  MethodHandle 绑定
    // ================================================================

    /**
     * 生成所有函数的 MethodHandle 静态字段和初始化
     */
    public String generateMethodHandles() {
        Map<String, ExternFunction> functions = bindingTable.getAllFunctions();
        if (functions.isEmpty()) return "";

        StringBuilder sb = new StringBuilder();
        sb.append("    /* ========== Method Handles ========== */\n");

        // 声明字段
        for (ExternFunction func : functions.values()) {
            sb.append("    private static final MethodHandle MH_")
              .append(func.name).append(";\n");
        }

        sb.append("\n    static {\n");
        for (ExternFunction func : functions.values()) {
            sb.append(generateMethodHandleInit(func));
        }
        sb.append("    }\n\n");
        return sb.toString();
    }

    private String generateMethodHandleInit(ExternFunction func) {
        StringBuilder sb = new StringBuilder();
        String lookupVar = resolveLookupVar(func);

        sb.append("        MH_").append(func.name).append(" = LINKER.downcallHandle(\n");
        sb.append("            findSymbol(").append(lookupVar).append(", \"")
          .append(func.name).append("\"),\n");
        sb.append("            FunctionDescriptor.of(\n");

        // 返回类型 layout
        sb.append("                ").append(mapToValueLayout(func.returnType));
        for (ExternParam param : func.params) {
            sb.append(",\n                ").append(mapToValueLayout(param.type));
        }

        sb.append("\n            )\n");
        sb.append("        );\n");
        return sb.toString();
    }

    // ================================================================
    //  包装方法
    // ================================================================

    /**
     * 生成高层 Java 包装方法
     */
    public String generateWrapperMethods() {
        Map<String, ExternFunction> functions = bindingTable.getAllFunctions();
        if (functions.isEmpty()) return "";

        StringBuilder sb = new StringBuilder();
        sb.append("    /* ========== Wrapper Methods ========== */\n");

        for (ExternFunction func : functions.values()) {
            sb.append(generateSingleWrapperMethod(func));
            sb.append("\n");
        }

        return sb.toString();
    }

    private String generateSingleWrapperMethod(ExternFunction func) {
        StringBuilder sb = new StringBuilder();
        String returnType = mapToJavaType(func.returnType);

        // 方法签名
        sb.append("    public static ").append(returnType).append(" ")
          .append(func.name).append("(");

        // 参数列表（添加 Arena 作为第一个参数）
        sb.append("Arena arena");
        for (ExternParam param : func.params) {
            sb.append(", ").append(mapToJavaType(param.type)).append(" ").append(param.name);
        }
        sb.append(") {\n");

        // 转换参数
        for (ExternParam param : func.params) {
            if ("String".equals(param.type) || "CString".equals(param.type)) {
                sb.append("        MemorySegment ").append(param.name).append("_c = ")
                  .append("toCString(arena, ").append(param.name).append(");\n");
            }
        }

        // 调用 MethodHandle
        sb.append("        try {\n");
        if (!"Void".equals(func.returnType)) {
            sb.append("            return (")
              .append(mapToJavaBoxedType(func.returnType)).append(") ");
        } else {
            sb.append("            ");
        }
        sb.append("MH_").append(func.name).append(".invokeExact(");

        for (int i = 0; i < func.params.size(); i++) {
            if (i > 0) sb.append(", ");
            ExternParam param = func.params.get(i);
            if ("String".equals(param.type) || "CString".equals(param.type)) {
                sb.append(param.name).append("_c");
            } else {
                sb.append(param.name);
            }
        }
        sb.append(");\n");
        sb.append("        } catch (Throwable t) {\n");
        sb.append("            throw new RuntimeException(\"FFI call failed: ")
          .append(func.name).append("\", t);\n");
        sb.append("        }\n");
        sb.append("    }\n");
        return sb.toString();
    }

    // ================================================================
    //  辅助方法
    // ================================================================

    public String generateHelperMethods() {
        StringBuilder sb = new StringBuilder();
        sb.append("    /* ========== Helper Methods ========== */\n");

        // toCString
        sb.append("    private static MemorySegment toCString(Arena arena, String str) {\n");
        sb.append("        if (str == null) return MemorySegment.NULL;\n");
        sb.append("        return arena.allocateFrom(str, StandardCharsets.UTF_8);\n");
        sb.append("    }\n\n");

        // fromCString
        sb.append("    private static String fromCString(MemorySegment segment) {\n");
        sb.append("        if (segment == null || segment.equals(MemorySegment.NULL)) return null;\n");
        sb.append("        return segment.getString(0, StandardCharsets.UTF_8);\n");
        sb.append("    }\n\n");

        // findSymbol
        List<String> libNames = bindingTable.getLibraryNames();
        if (!libNames.isEmpty()) {
            sb.append("    private static MemorySegment findSymbol(SymbolLookup lookup, String name) {\n");
            sb.append("        return lookup.find(name)\n");
            sb.append("            .orElseThrow(() -> new UnsatisfiedLinkError(\"Symbol not found: \" + name));\n");
            sb.append("    }\n");
        }

        return sb.toString();
    }

    // ================================================================
    //  类型映射
    // ================================================================

    /**
     * Claw FFI 类型 → Java 包装类型
     */
    public static String mapToJavaType(String clawType) {
        if (clawType == null) return "void";
        switch (clawType) {
            case "Void":     return "void";
            case "Int":      return "int";
            case "Float":    return "double";
            case "String":   return "String";
            case "CString":  return "String";
            case "Bool":     return "boolean";
            case "Any":
            case "Pointer":
            case "OpaquePointer":
            case "FuncPointer":
                return "MemorySegment";
            default:
                if (clawType.startsWith("Ref<") || clawType.startsWith("CArray<")) {
                    return "MemorySegment";
                }
                return "MemorySegment";
        }
    }

    /**
     * Claw FFI 类型 → Java 装箱类型（用于强制转换）
     */
    private static String mapToJavaBoxedType(String clawType) {
        switch (clawType) {
            case "Int":      return "Integer";
            case "Float":    return "Double";
            case "Bool":     return "Boolean";
            default:         return mapToJavaType(clawType);
        }
    }

    /**
     * Claw FFI 类型 → Panama ValueLayout
     */
    public static String mapToValueLayout(String clawType) {
        if (clawType == null) return "ValueLayout.JAVA_VOID";
        switch (clawType) {
            case "Void":     return "ValueLayout.JAVA_VOID";
            case "Int":      return "ValueLayout.JAVA_INT";
            case "Float":    return "ValueLayout.JAVA_DOUBLE";
            case "Bool":     return "ValueLayout.JAVA_BOOLEAN";
            case "String":
            case "CString":
                return "ValueLayout.ADDRESS";
            case "Pointer":
            case "OpaquePointer":
            case "FuncPointer":
            case "Any":
                return "ValueLayout.ADDRESS";
            default:
                if (clawType.startsWith("Ref<") || clawType.startsWith("CArray<")) {
                    return "ValueLayout.ADDRESS";
                }
                return "ValueLayout.ADDRESS";
        }
    }

    /**
     * 常量类型映射
     */
    private String mapToJavaConstantType(String type) {
        if (type == null) return "int";
        switch (type) {
            case "Int":     return "int";
            case "Float":   return "double";
            case "Bool":    return "boolean";
            case "String":  return "String";
            default:        return "int";
        }
    }

    // ================================================================
    //  Struct 定义生成
    // ================================================================

    /**
     * 生成 Java 类表示 C struct
     */
    public String generateStructDefinitions() {
        if (bindingTable.getAllStructs().isEmpty()) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        sb.append("\n    /* ========== Struct Definitions ========== */\n");

        for (ExternStruct struct : bindingTable.getAllStructs()) {
            sb.append(generateStructClass(struct));
        }

        return sb.toString();
    }

    private String generateStructClass(ExternStruct struct) {
        StringBuilder sb = new StringBuilder();
        int size = struct.estimateSize();
        int alignment = struct.alignment > 0 ? struct.alignment : 8;

        sb.append("    /** C struct: ").append(struct.name).append(" */\n");
        sb.append("    public static final class ").append(struct.name).append(" {\n");

        for (StructField field : struct.fields) {
            sb.append("        public ").append(mapToJavaType(field.type))
              .append(" ").append(field.name).append(";\n");
        }

        sb.append("    }\n\n");
        return sb.toString();
    }

    // ================================================================
    //  Enum 定义生成
    // ================================================================

    /**
     * 生成 Java 枚举表示 C enum
     */
    public String generateEnumDefinitions() {
        if (bindingTable.getAllEnums().isEmpty()) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        sb.append("\n    /* ========== Enum Definitions ========== */\n");

        for (ExternEnum enumType : bindingTable.getAllEnums()) {
            sb.append("    public enum ").append(enumType.name).append(" {\n");
            for (int i = 0; i < enumType.members.size(); i++) {
                EnumMember member = enumType.members.get(i);
                sb.append("        ").append(member.name);
                if (i < enumType.members.size() - 1) sb.append(",");
                sb.append("\n");
            }
            sb.append("    }\n\n");
        }

        return sb.toString();
    }

    // ================================================================
    //  Callback 定义生成
    // ================================================================

    /**
     * 生成 Java 函数接口表示 C callback
     */
    public String generateCallbackDefinitions() {
        if (bindingTable.getAllCallbacks().isEmpty()) {
            return "";
        }

        StringBuilder sb = new StringBuilder();
        sb.append("\n    /* ========== Callback Definitions ========== */\n");

        for (ExternCallback callback : bindingTable.getAllCallbacks()) {
            sb.append("    @FunctionalInterface\n");
            sb.append("    public interface ").append(callback.name).append(" {\n");
            sb.append("        ").append(mapToJavaType(callback.returnType)).append(" invoke(");

            for (int i = 0; i < callback.params.size(); i++) {
                if (i > 0) sb.append(", ");
                sb.append(mapToJavaType(callback.params.get(i).type))
                  .append(" ").append(callback.params.get(i).name);
            }
            sb.append(");\n    }\n\n");
        }

        return sb.toString();
    }

    // ================================================================
    //  辅助方法
    // ================================================================

    private String resolveLookupVar(ExternFunction func) {
        if (func.libraryName != null && !func.libraryName.isEmpty()) {
            return toSafeJavaName(func.libraryName).toUpperCase() + "_LOOKUP";
        }
        List<String> libs = bindingTable.getLibraryNames();
        if (!libs.isEmpty()) {
            return toSafeJavaName(libs.get(0)).toUpperCase() + "_LOOKUP";
        }
        return "UNKNOWN_LOOKUP";
    }

    private static String toSafeJavaName(String name) {
        return name.replaceAll("[^a-zA-Z0-9_]", "_");
    }
}
