package com.q3lives.ir;



/**
 * IR节点类型枚举
 */
public enum IRNodeType {
    // 模块级
    MODULE, IMPORT, EXPORT,
    // 类型定义
    TYPE_DEFINITION, FIELD_DECLARATION,
    // 函数相关
    FUNCTION_DECLARATION, PARAMETER, RETURN_STATEMENT,
    // 变量
    VARIABLE_DECLARATION, ASSIGNMENT,
    // 控制流
    IF_STATEMENT, ELSE_BRANCH, FOR_LOOP, WHILE_LOOP,
    BREAK_STATEMENT, CONTINUE_STATEMENT,
    // 表达式
    BINARY_EXPRESSION, UNARY_EXPRESSION, FUNCTION_CALL,
    MEMBER_ACCESS, ARRAY_ACCESS, LITERAL,
    // 操作流
    NORMAL_FLOW, EXCEPTION_FLOW, BUSINESS_FLOW,
    CATCH_BLOCK, FLOW_TO,
    // 注解
    ANNOTATION_NODE,
    // 代码块
    BLOCK
}