package claw.compiler.generators.ffi;

import claw.compiler.generators.ffi.FFIBindingTable.*;

import java.util.*;

/**
 * Java 目标 FFI 代码生成器
 *
 * 将 FFIBindingTable 中的外部符号信息转换为 Java FFI 代码
 *
 * 使用 Java 22+ 的 Foreign Function & Memory API（Project Panama）
 *
 * 策略：
 *   - link "sqlite3"  → System.loadLibrary / SymbolLookup.libraryLookup
 *   - extern function → Linker.downcallHandle + FunctionDescriptor
 *   - extern type     → MemorySegment（不透明指针）
 *   - extern const    → static final 字段
 *
 * 对于不支持 Panama 的低版本 Java，可降级为 JNI
 */
public class JavaFFIGenerator {

    /**
     * 代码生成策略
     */
    public enum Strategy {
        PANAMA,     // Java 22+ Foreign Function & Memory API
        JNI         // 传统 JNI（降级方案）
    }

    private final FFIBindingTable bindingTable;
    private final Strategy strategy;
    private final String packageName;

    /**
     * @param bindingTable  FFI 绑定表
     * @param strategy      生成策略（PANAMA 或 JNI）
     * @param packageName   生成代码的 Java 包名
     */
    public JavaFFIGenerator(FFIBindingTable bindingTable, Strategy strategy, String packageName) {
        this.bindingTable = bindingTable;
        this.strategy = strategy;
        this.packageName = packageName;
    }

    /**
     * 默认构造：使用 Panama 策略
     */
    public JavaFFIGenerator(FFIBindingTable bindingTable) {
        this(bindingTable, Strategy.PANAMA, "claw.generated");
    }

    // ================================================================
    //  生成完整的 FFI 绑定类
    // ================================================================

    /**
     * 生成完整的 Java FFI 绑定类
     *
     * 类名基于第一个链接库名，如 "sqlite3" -> "Sqlite3FFI"
     */
    public String generateAll() {
        if (!bindingTable.hasExternDeclarations()) {
            return "";
        }

        if (strategy == Strategy.PANAMA) {
            return generatePanamaBinding();
        } else {
            return generateJNIBinding();
        }
    }

    // ================================================================
    //  Panama 策略代码生成
    // ================================================================

    private String generatePanamaBinding() {
        String className = getBindingClassName();

        StringBuilder sb = new StringBuilder();

        // 文件头
        sb.append("package ").append(packageName).append(";\n");
        sb.append(generatePanamaImports());

        sb.append("/**\n");
        sb.append(" * FFI Bindings (auto-generated by Claw Compiler)\n");
        sb.append(" * Strategy: Panama (Java 22+ Foreign Function & Memory API)\n");
        sb.append(" *\n");
        sb.append(" * Libraries: ");
        for (LinkDirective link : bindingTable.getAllLinks()) {
            sb.append(link.libraryName).append(" ");
        }
        sb.append("\n");
        sb.append(" */\n");
        sb.append("public final class ").append(className).append(" {\n");

        // 私有构造函数
        sb.append("    private ").append(className).append("() {}\n");

        // 静态初始化
        sb.append(generatePanamaStaticInit());

        // 常量
        sb.append(generatePanamaConstants());

        // Arena 工具方法
        sb.append(generateArenaHelpers());

        // 函数绑定
        sb.append(generatePanamaFunctionHandles());

        // 包装方法
        sb.append(generatePanamaWrapperMethods());

        sb.append("}\n");

        return sb.toString();
    }

    /**
     * 生成 Panama import 语句
     */
    private String generatePanamaImports() {
        StringBuilder sb = new StringBuilder();
        sb.append("import java.lang.foreign.*;\n");
        sb.append("import java.lang.invoke.MethodHandle;\n");
        sb.append("import java.nio.charset.StandardCharsets;\n");
        return sb.toString();
    }

    /**
     * 生成静态初始化块：加载库、获取 Linker
     */
    private String generatePanamaStaticInit() {
        StringBuilder sb = new StringBuilder();
        sb.append("    // ==================== Library Loading ====================\n");
        sb.append("    private static final Linker LINKER = Linker.nativeLinker();\n");

        // 为每个库生成 SymbolLookup
        for (LinkDirective link : bindingTable.getAllLinks()) {
            String varName = toConstantName(link.libraryName) + "_LOOKUP";
            sb.append("    private static final SymbolLookup ").append(varName).append(";\n");
        }

        sb.append("\n    static {\n");
        sb.append("        try {\n");

        for (LinkDirective link : bindingTable.getAllLinks()) {
            String varName = toConstantName(link.libraryName) + "_LOOKUP";
            sb.append("            ").append(varName).append(" = SymbolLookup.libraryLookup(\n");
            sb.append("                System.mapLibraryName(\"").append(link.libraryName).append("\"),\n");
            sb.append("                Arena.global()\n");
            sb.append("            );\n");
        }

        sb.append("        } catch (Exception e) {\n");
        sb.append("            throw new ExceptionInInitializerError(\n");
        sb.append("                \"Failed to load native library: \" + e.getMessage()\n");
        sb.append("            );\n");
        sb.append("        }\n");
        sb.append("    }\n");

        // 便捷方法：查找符号
        sb.append("    /**\n");
        sb.append("     * 在所有已加载的库中查找符号\n");
        sb.append("     */\n");
        sb.append("    private static MemorySegment findSymbol(String name) {\n");

        List<LinkDirective> links = bindingTable.getAllLinks();
        for (int i = 0; i < links.size(); i++) {
            String varName = toConstantName(links.get(i).libraryName) + "_LOOKUP";
            if (i == 0) {
                sb.append("        var opt = ").append(varName).append(".find(name);\n");
            } else {
                sb.append("        if (opt.isEmpty()) opt = ").append(varName).append(".find(name);\n");
            }
        }

        sb.append("        return opt.orElseThrow(() ->\n");
        sb.append("            new UnsatisfiedLinkError(\"Symbol not found: \" + name));\n");
        sb.append("    }\n");

        return sb.toString();
    }

    /**
     * 生成常量定义
     */
    private String generatePanamaConstants() {
        Map<String, ExternConstant> constants = bindingTable.getAllConstants();
        if (constants.isEmpty()) return "";

        StringBuilder sb = new StringBuilder();
        sb.append("    // ==================== Constants ====================\n");

        for (ExternConstant constant : constants.values()) {
            String javaType = mapClawTypeToJavaType(constant.type);
            sb.append("    public static final ").append(javaType).append(" ")
              .append(constant.name).append(" = ").append(constant.value).append(";\n");
        }

        //sb.append("\n");
        return sb.toString();
    }

    /**
     * 生成 Arena 工具方法
     */
    private String generateArenaHelpers() {
        StringBuilder sb = new StringBuilder();
        sb.append("    // ==================== Arena Helpers ====================\n");

        sb.append("    /**\n");
        sb.append("     * 将 Java String 转换为 C 字符串（MemorySegment）\n");
        sb.append("     */\n");
        sb.append("    public static MemorySegment toCString(Arena arena, String str) {\n");
        sb.append("        if (str == null) return MemorySegment.NULL;\n");
        sb.append("        return arena.allocateFrom(str, StandardCharsets.UTF_8);\n");
        sb.append("    }\n");

        sb.append("    /**\n");
        sb.append("     * 将 C 字符串（MemorySegment）转换为 Java String\n");
        sb.append("     */\n");
        sb.append("    public static String fromCString(MemorySegment segment) {\n");
        sb.append("        if (segment == null || segment.equals(MemorySegment.NULL)) return null;\n");
        sb.append("        return segment.getString(0, StandardCharsets.UTF_8);\n");
        sb.append("    }\n");

        sb.append("    /**\n");
        sb.append("     * 分配一个指针大小的内存（用于 Ref<T> 即传出参数）\n");
        sb.append("     */\n");
        sb.append("    public static MemorySegment allocatePointer(Arena arena) {\n");
        sb.append("        return arena.allocate(ValueLayout.ADDRESS);\n");
        sb.append("    }\n");

        sb.append("    /**\n");
        sb.append("     * 从指针段中读取指针值\n");
        sb.append("     */\n");
        sb.append("    public static MemorySegment readPointer(MemorySegment ptrSegment) {\n");
        sb.append("        return ptrSegment.get(ValueLayout.ADDRESS, 0);\n");
        sb.append("    }\n");

        return sb.toString();
    }

    /**
     * 生成 MethodHandle（下调句柄）
     */
    private String generatePanamaFunctionHandles() {
        Map<String, ExternFunction> functions = bindingTable.getAllFunctions();
        if (functions.isEmpty()) return "";

        StringBuilder sb = new StringBuilder();
        sb.append("    // ==================== Function Handles ====================\n");

        for (ExternFunction func : functions.values()) {
            String handleName = "MH_" + func.name;

            sb.append("    private static final MethodHandle ").append(handleName).append(";\n");
        }

        sb.append("    static {\n");

        for (ExternFunction func : functions.values()) {
            String handleName = "MH_" + func.name;

            // FunctionDescriptor
            sb.append("        ").append(handleName).append(" = LINKER.downcallHandle(\n");
            sb.append("            findSymbol(\"").append(func.name).append("\"),\n");
            sb.append("            ");

            if ("Void".equals(func.returnType)) {
                sb.append("FunctionDescriptor.ofVoid(");
            } else {
                sb.append("FunctionDescriptor.of(\n");
                sb.append("                ").append(mapClawTypeToMemoryLayout(func.returnType));
                if (!func.params.isEmpty()) {
                    sb.append(",");
                }
            }

            // 参数布局
            for (int i = 0; i < func.params.size(); i++) {
                if (i > 0 || !"Void".equals(func.returnType)) {
                    sb.append("\n                ");
                }
                sb.append(mapClawTypeToMemoryLayout(func.params.get(i).type));
                if (i < func.params.size() - 1) {
                    sb.append(",");
                }
            }

            sb.append("\n            )\n        );\n");
        }

        sb.append("    }\n");
        return sb.toString();
    }

    /**
     * 生成高层包装方法
     */
    private String generatePanamaWrapperMethods() {
        Map<String, ExternFunction> functions = bindingTable.getAllFunctions();
        if (functions.isEmpty()) return "";

        StringBuilder sb = new StringBuilder();
        sb.append("    // ==================== Public API Methods ====================\n");

        for (ExternFunction func : functions.values()) {
            sb.append(generateSinglePanamaMethod(func));
            sb.append("\n");
        }

        return sb.toString();
    }

    /**
     * 为单个函数生成 Panama 包装方法
     */
    private String generateSinglePanamaMethod(ExternFunction func) {
        StringBuilder sb = new StringBuilder();
        String handleName = "MH_" + func.name;
        String javaReturnType = mapClawTypeToJavaType(func.returnType);

        // 判断是否需要 Arena 参数（有 String 输入或 Ref 参数时）
        boolean needsArena = false;
        for (ExternParam param : func.params) {
            if ("String".equals(param.type) || "CString".equals(param.type)
                || param.type.startsWith("Ref<")) {
                needsArena = true;
                break;
            }
        }

        // Javadoc
        sb.append("    /**\n");
        sb.append("     * ").append(func.name).append("\n");
        sb.append("     *\n");
        sb.append("     * Native signature: ").append(func).append("\n");
        sb.append("     */\n");

        // 方法签名
        sb.append("    public static ").append(javaReturnType).append(" ").append(func.name).append("(");

        if (needsArena) {
            sb.append("Arena arena");
            if (!func.params.isEmpty()) sb.append(", ");
        }

        for (int i = 0; i < func.params.size(); i++) {
            if (i > 0) sb.append(", ");
            ExternParam param = func.params.get(i);
            sb.append(mapClawTypeToJavaParamType(param.type)).append(" ").append(param.name);
        }

        sb.append("){\n");

        // 方法体
        sb.append("        try {\n");

        // 参数转换
        List<String> callArgs = new ArrayList<>();
        for (ExternParam param : func.params) {
            if ("String".equals(param.type) || "CString".equals(param.type)) {
                String cVar = param.name + "_c";
                sb.append("            MemorySegment ").append(cVar)
                  .append(" = toCString(arena, ").append(param.name).append(");\n");
                callArgs.add(cVar);
            } else if (param.type.startsWith("Ref<")) {
                // Ref<T> 已经是 MemorySegment（调用前由调用者通过 allocatePointer 创建）
                callArgs.add(param.name);
            } else if ("Pointer".equals(param.type) || "OpaquePointer".equals(param.type)
                       || isExternType(param.type)) {
                callArgs.add(param.name);
            } else {
                callArgs.add(param.name);
            }
        }

        // 调用 MethodHandle
        if ("Void".equals(func.returnType) || "void".equals(javaReturnType)) {
            sb.append("            ").append(handleName).append(".invokeExact(");
            sb.append(String.join(", ", callArgs));
            sb.append(");\n");
        } else if ("String".equals(func.returnType) || "CString".equals(func.returnType)) {
            sb.append("            MemorySegment _result = (MemorySegment) ").append(handleName)
              .append(".invokeExact(");
            sb.append(String.join(", ", callArgs));
            sb.append(");\n");
            sb.append("            return fromCString(_result);\n");
        } else if ("Int".equals(func.returnType) || "Int32".equals(func.returnType)) {
            sb.append("            return (int) ").append(handleName).append(".invokeExact(");
            sb.append(String.join(", ", callArgs));
            sb.append(");\n");
        } else if ("Int64".equals(func.returnType)) {
            sb.append("            return (long) ").append(handleName).append(".invokeExact(");
            sb.append(String.join(", ", callArgs));
            sb.append(");");
        } else if ("Float".equals(func.returnType)) {
            sb.append("            return (double) ").append(handleName).append(".invokeExact(");
            sb.append(String.join(", ", callArgs));
            sb.append(");\n");
        } else if ("Bool".equals(func.returnType)) {
            sb.append("            return (boolean) ").append(handleName).append(".invokeExact(");
            sb.append(String.join(", ", callArgs));
            sb.append(");\n");
        } else {
            // Pointer / OpaquePointer / 自定义类型 → MemorySegment
            sb.append("            return (MemorySegment) ").append(handleName).append(".invokeExact(");
            sb.append(String.join(", ", callArgs));
            sb.append(");\n");
        }

        sb.append("        } catch (Throwable t) {\n");
        sb.append("            throw new RuntimeException(\"FFI call failed: ").append(func.name)
          .append("\", t);\n");
        sb.append("        }\n");
        sb.append("\n");        sb.append("    }\n");

        return sb.toString();
    }

    // ================================================================
    //  JNI 降级策略代码生成
    // ================================================================

    private String generateJNIBinding() {
        String className = getBindingClassName();

        StringBuilder sb = new StringBuilder();

        sb.append("package ").append(packageName).append(";\n");
        sb.append("/**");
        sb.append(" * FFI Bindings (auto-generated by Claw Compiler)\n");
        sb.append(" * Strategy: JNI (Java Native Interface)\n");
        sb.append(" *");
        sb.append(" * Note: Requires native JNI bridge library.\n");
        sb.append(" * Compile the generated .c JNI bridge with:");
        sb.append(" *   gcc -shared -fPIC -I\"$JAVA_HOME/include\" -I\"$JAVA_HOME/include/linux\" \\\n");
        sb.append(" *       -o libclaw_jni_bridge.so claw_jni_bridge.c");
        for (LinkDirective link : bindingTable.getAllLinks()) {
            sb.append(" -l").append(link.libraryName);
        }
        sb.append("\n");
        sb.append(" */\n");
        sb.append("public final class ").append(className).append(" {\n");

        // 加载 JNI 库
        sb.append("    static {\n");
        sb.append("        System.loadLibrary(\"claw_jni_bridge\");\n");
        sb.append("    }\n");

        // 常量
        for (ExternConstant constant : bindingTable.getAllConstants().values()) {
            String javaType = mapClawTypeToJavaType(constant.type);
            sb.append("    public static final ").append(javaType).append(" ")
              .append(constant.name).append(" = ").append(constant.value).append(";\n");
        }
        sb.append("\n");

        // native 方法声明
        sb.append("    // ==================== Native Methods ====================\n");
        for (ExternFunction func : bindingTable.getAllFunctions().values()) {
            String javaReturnType = mapClawTypeToJNIType(func.returnType);
            sb.append("    public static native ").append(javaReturnType)
              .append(" ").append(func.name).append("(");

            for (int i = 0; i < func.params.size(); i++) {
                if (i > 0) sb.append(", ");
                ExternParam param = func.params.get(i);
                sb.append(mapClawTypeToJNIType(param.type)).append(" ").append(param.name);
            }

            sb.append(");\n");
        }

        sb.append("\n");

        // 私有构造函数
        sb.append("    private ").append(className).append("() {}\n");
        sb.append("}\n");

        return sb.toString();
    }

    // ================================================================
    //  类型映射
    // ================================================================

    /**
     * Claw FFI 类型 → Java 类型（Panama 策略）
     */
    public static String mapClawTypeToJavaType(String clawType) {
        if (clawType == null) return "void";

        switch (clawType) {
            case "Void":    return "void";
            case "Int":     return "int";
            case "Float":   return "double";
            case "String":  return "String";
            case "CString": return "String";
            case "Bool":    return "boolean";
            case "Any":     return "MemorySegment";

            case "Pointer":       return "MemorySegment";
            case "OpaquePointer": return "MemorySegment";
            case "FuncPointer":   return "MemorySegment";
            case "SizeT":         return "long";

            case "Int8":   return "byte";
            case "Int16":  return "short";
            case "Int32":  return "int";
            case "Int64":  return "long";
            case "UInt8":  return "byte";
            case "UInt16": return "short";
            case "UInt32": return "int";
            case "UInt64": return "long";

            default:
                if (clawType.startsWith("Ref<") || clawType.startsWith("CArray<")) {
                    return "MemorySegment";
                }
                return "MemorySegment";
        }
    }

    /**
     * Claw FFI 类型 → Java 方法参数类型（Panama 策略）
     * String 参数保持为 String（在方法内部转换）
     */
    private String mapClawTypeToJavaParamType(String clawType) {
        if ("String".equals(clawType) || "CString".equals(clawType)) {
            return "String";
        }
        return mapClawTypeToJavaType(clawType);
    }

    /**
     * Claw FFI 类型 → MemoryLayout（Panama FunctionDescriptor 用）
     */
    public static String mapClawTypeToMemoryLayout(String clawType) {
        if (clawType == null) return "ValueLayout.ADDRESS";

        switch (clawType) {
            case "Int":     return "ValueLayout.JAVA_INT";
            case "Float":   return "ValueLayout.JAVA_DOUBLE";
            case "Bool":    return "ValueLayout.JAVA_BOOLEAN";
            case "String":  return "ValueLayout.ADDRESS";
            case "CString": return "ValueLayout.ADDRESS";
            case "Any":     return "ValueLayout.ADDRESS";

            case "Pointer":       return "ValueLayout.ADDRESS";
            case "OpaquePointer": return "ValueLayout.ADDRESS";
            case "FuncPointer":   return "ValueLayout.ADDRESS";
            case "SizeT":         return "ValueLayout.JAVA_LONG";

            case "Int8":   return "ValueLayout.JAVA_BYTE";
            case "Int16":  return "ValueLayout.JAVA_SHORT";
            case "Int32":  return "ValueLayout.JAVA_INT";
            case "Int64":  return "ValueLayout.JAVA_LONG";
            case "UInt8":  return "ValueLayout.JAVA_BYTE";
            case "UInt16": return "ValueLayout.JAVA_SHORT";
            case "UInt32": return "ValueLayout.JAVA_INT";
            case "UInt64": return "ValueLayout.JAVA_LONG";

            default:
                if (clawType.startsWith("Ref<") || clawType.startsWith("CArray<")) {
                    return "ValueLayout.ADDRESS";
                }
                return "ValueLayout.ADDRESS";
        }
    }

    /**
     * Claw FFI 类型 → JNI 类型（JNI 降级策略）
     */
    private String mapClawTypeToJNIType(String clawType) {
        if (clawType == null) return "void";

        switch (clawType) {
            case "Void":    return "void";
            case "Int":     return "int";
            case "Float":   return "double";
            case "String":  return "String";
            case "CString": return "String";
            case "Bool":    return "boolean";
            case "Any":     return "long";

            case "Pointer":       return "long";
            case "OpaquePointer": return "long";
            case "SizeT":         return "long";

            case "Int8":   return "byte";
            case "Int16":  return "short";
            case "Int32":  return "int";
            case "Int64":  return "long";

            default:
                if (clawType.startsWith("Ref<") || clawType.startsWith("CArray<")) {
                    return "long";  // 指针作为 long 传递
                }
                return "long";
        }
    }

    /**
     * 生成 Java 运行时平台检测
     */
    public String generatePlatformDetection() {
        StringBuilder sb = new StringBuilder();

        sb.append("/**\n");    sb.append(" * Claw FFI 平台检测工具\n");
        sb.append(" */\n");
        sb.append("final class ClawPlatform {\n");
    
        sb.append("    enum OS { WINDOWS, LINUX, MACOS, FREEBSD, ANDROID, UNKNOWN }\n");
        sb.append("    enum Arch { X86_64, ARM64, X86, ARM, UNKNOWN }\n");
    
        sb.append("    static final OS CURRENT_OS;\n");
        sb.append("    static final Arch CURRENT_ARCH;\n");
    
        sb.append("    static {\\n");
        sb.append("        String osName = System.getProperty(\"os.name\", \"\").toLowerCase();\n");
        sb.append("        if (osName.contains(\"win\"))        CURRENT_OS = OS.WINDOWS;\n");
        sb.append("        else if (osName.contains(\"mac\"))   CURRENT_OS = OS.MACOS;\n");
        sb.append("        else if (osName.contains(\"linux\")) CURRENT_OS = OS.LINUX;\n");
        sb.append("        else if (osName.contains(\"freebsd\")) CURRENT_OS = OS.FREEBSD;\n");
        sb.append("        else                                CURRENT_OS = OS.UNKNOWN;\n");
    
        sb.append("        String arch = System.getProperty(\"os.arch\", \"\").toLowerCase();\n");
        sb.append("        if (arch.contains(\"amd64\") || arch.contains(\"x86_64\")) CURRENT_ARCH = Arch.X86_64;\n");
        sb.append("        else if (arch.contains(\"aarch64\") || arch.contains(\"arm64\")) CURRENT_ARCH = Arch.ARM64;\n");
        sb.append("        else if (arch.contains(\"x86\") || arch.contains(\"i386\")) CURRENT_ARCH = Arch.X86;\n");
        sb.append("        else if (arch.contains(\"arm\"))     CURRENT_ARCH = Arch.ARM;\n");
        sb.append("        else                                CURRENT_ARCH = Arch.UNKNOWN;");
        sb.append("    }\n");
    
        sb.append("    static boolean isPlatform(OS... targets) {\n");
        sb.append("        for (OS t : targets) if (t == CURRENT_OS) return true;\n");
        sb.append("        return false;\n");
        sb.append("    }\n");
    
        sb.append("    static boolean isArch(Arch... targets) {\n");
        sb.append("        for (Arch t : targets) if (t == CURRENT_ARCH) return true;\n");
        sb.append("        return false;\n");
        sb.append("    }\n");
    
        // 库文件名生成
        sb.append("    static String libraryFileName(String name) {\n");
        sb.append("        return switch (CURRENT_OS) {");
        sb.append("            case WINDOWS -> name + \".dll\";\n");
        sb.append("            case MACOS   -> \"lib\" + name + \".dylib\";\n");
        sb.append("            default      -> \"lib\" + name + \".so\";\n");
        sb.append("        };\n");
        sb.append("    }\n");
    
        sb.append("}new\n");
    
        return sb.toString();
    }
    
    /**
     * 生成平台条件绑定（Java Panama）
     *
     * Java 无法用预处理器，使用运行时判断 + 策略模式
     */
    public String generatePlatformConditionalBindings(FFIBindingTable fullTable) {
        StringBuilder sb = new StringBuilder();
    
        sb.append("/**\n");
        sb.append(" * 平台自适应的 FFI 绑定加载\n");
        sb.append(" */\n");
        sb.append("static void loadPlatformBindings() {\n");
    
        boolean first = true;
        for (FFIBindingTable.ExternBlock block : fullTable.getExternBlocks()) {
            if (block.platform != null && !block.platform.isUniversal()) {
                if (!first) sb.append("    else ");
                else sb.append("    ");
                first = false;
    
                sb.append(generateJavaPlatformCondition(block.platform)).append(" {\\n");
    
                // 加载该平台的库和函数
                for (FFIBindingTable.LinkDirective link : block.links) {
                    sb.append("        loadLibrary(\"").append(link.libraryName).append("\");\n");
                }
                for (FFIBindingTable.ExternFunction func : block.functions) {
                    sb.append("        bindFunction(\"").append(func.name).append("\");\n");
                }
    
                sb.append("    }\n");
            }
        }
    
        sb.append("}\n");
        return sb.toString();
    }
    
    private String generateJavaPlatformCondition(FFIBindingTable.PlatformConstraint constraint) {
        List<String> conditions = new ArrayList<>();
    
        for (String p : constraint.getPlatforms()) {
            conditions.add("ClawPlatform.isPlatform(ClawPlatform.OS."
                + p.toUpperCase() + ")");
        }
        for (String a : constraint.getArchitectures()) {
            conditions.add("ClawPlatform.isArch(ClawPlatform.Arch."
                + a.toUpperCase() + ")");
        }
    
        return "if (" + String.join(" && ", conditions) + ")";
    }
    

    // ================================================================
    //  辅助方法
    // ================================================================

    /**
     * 生成绑定类名
     * "sqlite3" -> "Sqlite3FFI"
     */
    private String getBindingClassName() {
        List<LinkDirective> links = bindingTable.getAllLinks();
        if (links.isEmpty()) {
            return "ExternFFI";
        }
        String libName = links.get(0).libraryName;
        return toPascalCase(libName) + "FFI";
    }

    /**
     * 检查是否是 extern 定义的自定义类型
     */
    private boolean isExternType(String typeName) {
        return bindingTable.findType(typeName) != null;
    }

    private static String toPascalCase(String name) {
        if (name == null || name.isEmpty()) return name;
        StringBuilder sb = new StringBuilder();
        boolean capitalizeNext = true;
        for (char c : name.toCharArray()) {
            if (c == '_' || c == '-' || c == '.') {
                capitalizeNext = true;
            } else if (capitalizeNext) {
                sb.append(Character.toUpperCase(c));
                capitalizeNext = false;
            } else {
                sb.append(c);
            }
        }
        return sb.toString();
    }

    private static String toConstantName(String name) {
        return name.toUpperCase().replaceAll("[^A-Z0-9]", "_");
    }
}
