package com.q3lives.binding.python;

import com.q3lives.binding.GenerationConfig;
import com.q3lives.binding.GenerationResult;
import com.q3lives.binding.TargetCodeGenerator;
import com.q3lives.binding.TargetRuntime;
import com.q3lives.compiler.generators.IRGenerator;
import com.q3lives.compiler.generators.IRGenerator.IRBasicBlock;
import com.q3lives.compiler.generators.IRGenerator.IRInstruction;
import com.q3lives.compiler.generators.IRGenerator.IRProgram;
import com.q3lives.compiler.generators.IRGenerator.OpCode;
import com.q3lives.compiler.generators.ffi.FFIBindingTable;
import com.q3lives.compiler.generators.ffi.PythonFFIGenerator;
import com.q3lives.ir.ClawIR;
import java.util.*;
import java.util.stream.Collectors;
import java.util.HashMap;
import java.util.LinkedHashSet;

/**
 * 增强版Python目标语言代码生成器
 *
 * 完善了原有生成器的所有TODO功能：
 * 1. generateBlockLoadingCode - 生成代码块加载代码
 * 2. generateTryBody - 生成try代码体
 * 3. generateFinallyBody - 生成finally代码体
 * 4. extractPropertyListFromIR - 从IR提取属性列表
 * 5. 完整的"flow to"语句实现
 */
public class EnhancedPythonCodeGenerator implements TargetCodeGenerator {

    private final PythonRuntime runtime;
    private StringBuilder output;
    private int indentLevel;
    private List<String> currentFuncParams;  // 当前函数的参数列表
    private String stackTopVar;  // 当前栈顶变量名
    private IRProgram currentProgram;  // 当前IR程序
    private Map<String, List<String>> propertyMapping = new HashMap<>();  // 属性映射
    private Set<String> importedModules = new LinkedHashSet<>();  // 已导入的模块

    public EnhancedPythonCodeGenerator() {
        this.runtime = new PythonRuntime();
    }

    @Override
    public TargetRuntime getRuntime() {
        return runtime;
    }

    @Override
    public String getLanguageName() {
        return "Python";
    }

    @Override
    public String getFileExtension() {
        return ".py";
    }

    @Override
    public String generate(ClawIR ir) {
        output = new StringBuilder();
        indentLevel = 0;
        currentProgram = ir.getIrProgram();
        propertyMapping.clear();
        importedModules.clear();

        // 1. 文件头注释
        appendLine("#!/usr/bin/env python3");
        appendLine(runtime.generateComment("Auto-generated by Claw Compiler"));
        appendLine(runtime.generateComment("Target: Python 3.10+"));
        appendLine(runtime.generateComment("Source: " + currentProgram.getSourceFileName()));
        appendLine("");

        // 2. 必要的 import
        generateRequiredImports();

        // 3. 运行时辅助代码
        appendLine(runtime.generateRuntimeHelpers());
        appendLine("");

        // 4. 元数据（系统注解 @@description 等，生成为模块级 docstring）
        Map<String, Object> metadata = currentProgram.getMetadata();
        if (metadata != null && !metadata.isEmpty()) {
            Map<String, String> stringMetadata = new HashMap<>();
            for (Map.Entry<String, Object> entry : metadata.entrySet()) {
                stringMetadata.put(entry.getKey(), String.valueOf(entry.getValue()));
            }
            appendLine(runtime.generateDocComment(stringMetadata));
            appendLine("");
        }

        // 5. 从IR中提取属性列表
        extractPropertyListFromIR();

        // 6. 遍历所有顶层IR块，生成代码
        for (IRBasicBlock topBlock : currentProgram.getTopLevelBlocks()) {
            generateBlock(topBlock);
        }

        // 7. __main__ 入口
        appendLine("");
        appendLine("if __name__ == \"__main__\":");
        indentLevel++;
        appendLine("pass  # Entry point");
        indentLevel--;

        return output.toString();
    }

    @Override
    public GenerationResult generate(ClawIR ir, GenerationConfig defaultConfig) {
        GenerationResult result = new GenerationResult();
        if (ir == null) {
            result.addWarning("No IR provided for Python code generation.");
            return result;
        }

        String code = generate(ir);
        String fileName = "claw_output" + getFileExtension();
        result.addFile(fileName, code);

        // 如果包含 FFI 绑定，生成 FFI 代码
        if (ir.hasFFIBindings()) {
            FFIBindingTable ffiTable = ir.getFfiBindingTable();
            PythonFFIGenerator ffiGenerator = new PythonFFIGenerator(ffiTable);
            String ffiCode = ffiGenerator.generateAll();
            if (!ffiCode.isEmpty()) {
                result.addFile("claw_ffi_bindings.py", ffiCode);
            }
        }

        return result;
    }

    /**
     * 生成必要的import语句
     */
    private void generateRequiredImports() {
        // 收集所有需要的导入
        List<String> requiredImports = runtime.getRequiredImports();

        // 添加IR中需要的导入
        for (IRBasicBlock block : currentProgram.getTopLevelBlocks()) {
            collectImportsFromBlock(block, requiredImports);
        }

        // 生成导入语句
        for (String imp : requiredImports) {
            if (!importedModules.contains(imp)) {
                appendLine(imp);
                importedModules.add(imp);
            }
        }

        if (!requiredImports.isEmpty()) {
            appendLine("");
        }
    }

    /**
     * 从代码块收集导入
     */
    private void collectImportsFromBlock(IRBasicBlock block, Collection<String> imports) {
        for (IRInstruction inst : block.getInstructions()) {
            if (inst.getOpCode() == OpCode.IMPORT) {
                String module = inst.getOperands().get(0).toString();
                String symbol = inst.getOperands().size() > 1 ?
                    inst.getOperands().get(1).toString() : null;

                if (symbol != null) {
                    imports.add("from " + module + " import " + symbol);
                } else {
                    imports.add("import " + module);
                }
            }
        }

        // 递归处理子块
        for (IRBasicBlock child : block.getChildren()) {
            collectImportsFromBlock(child, imports);
        }
    }

    // ==================== 块遍历 ====================

    private void generateBlock(IRBasicBlock block) {
        // 处理当前块的所有指令
        for (IRInstruction inst : block.getInstructions()) {
            generateInstruction(inst);
        }

        // 递归处理子块
        if (block.getChildren() != null) {
            for (IRBasicBlock child : block.getChildren()) {
                generateBlock(child);
            }
        }
    }

    // ==================== 指令分派 ====================

    private void generateInstruction(IRInstruction inst) {
        OpCode opCode = inst.getOpCode();
        List<Object> ops = inst.getOperands();

        switch (opCode) {

            // ====== 控制流 ======
            case WHILE_LOOP: {
                String varName = ops.get(0).toString();
                String iterable = ops.size() > 1 ? ops.get(1).toString() : "__iterable";
                appendLine("for " + varName + " in " + iterable + ":");
                indentLevel++;
                break;
            }

            case BREAK_LOOP: {
                appendLine(runtime.generateBreak());
                break;
            }

            case CONTINUE_LOOP: {
                appendLine(runtime.generateContinue());
                break;
            }

            case TRY_BLOCK: {
                generateTryBody(inst);
                break;
            }

            case FINALLY: {
                generateFinallyBody(inst);
                break;
            }

            case MULTI_EXCEPTION_CATCH: {
                generateMultiExceptionCatch(inst);
                break;
            }

            // ====== 函数定义 ======
            case FUNC_DEF: {
                generateFunctionDefinition(inst);
                break;
            }

            case FUNC_END: {
                appendLine("");
                indentLevel = Math.max(0, indentLevel - 1);
                currentFuncParams = null;
                break;
            }

            // ====== 内存管理 ======
            case ALLOC: {
                generateAllocation(inst);
                break;
            }

            case DEALLOC: {
                generateDeallocation(inst);
                break;
            }

            // ====== 变量操作 ======
            case STORE_VAR: {
                generateStoreVariable(inst);
                break;
            }

            case LOAD_VAR: {
                generateLoadVariable(inst);
                break;
            }

            case LOAD_CONST: {
                generateLoadConstant(inst);
                break;
            }

            // ====== 运算 ======
            case ADD: case SUB: case MUL: case DIV: case MOD: {
                generateArithmeticOperation(inst);
                break;
            }

            case CMP_EQ: case CMP_NE: case CMP_LT: case CMP_GT:
            case CMP_LE: case CMP_GE: {
                generateComparisonOperation(inst);
                break;
            }

            case AND: case OR: case NOT: {
                generateLogicalOperation(inst);
                break;
            }

            // ====== 作用域 ======
            case SCOPE_ENTER: {
                generateScopeEnter(inst);
                break;
            }

            case SCOPE_EXIT: {
                generateScopeExit(inst);
                break;
            }

            // ====== 控制流 ======
            case JUMP: {
                generateJump(inst);
                break;
            }

            case JUMP_IF_TRUE: case JUMP_IF_FALSE: {
                generateConditionalJump(inst);
                break;
            }

            // ====== 属性监听钩子 ======
            case BEFORE_PROPS_HOOK: {
                generateBeforePropsHook(inst);
                break;
            }

            case AFTER_PROPS_HOOK: {
                generateAfterPropsHook(inst);
                break;
            }

            case BEFORE_NAME_HOOK: {
                generateBeforeNameHook(inst);
                break;
            }

            case AFTER_NAME_HOOK: {
                generateAfterNameHook(inst);
                break;
            }

            // ====== 属性读写 ======
            case PROP_SET: {
                generatePropertySet(inst);
                break;
            }

            // ====== 数组操作 ======
            case ARRAY_NEW: {
                generateArrayCreation(inst);
                break;
            }

            case ARRAY_GET: {
                generateArrayGet(inst);
                break;
            }

            case ARRAY_SET: {
                generateArraySet(inst);
                break;
            }

            // ====== 函数调用 ======
            case FUNC_CALL: {
                generateFunctionCall(inst);
                break;
            }

            case RETURN: {
                generateReturn(inst);
                break;
            }

            // ====== 三层操作流 ======
            case NORMAL_FLOW_BEGIN: {
                generateNormalFlowBegin(inst);
                break;
            }

            case NORMAL_FLOW_END: {
                generateNormalFlowEnd(inst);
                break;
            }

            case EXCEPTION_CATCH: {
                generateExceptionCatch(inst);
                break;
            }

            case EXCEPTION_THROWS: {
                generateExceptionThrows(inst);
                break;
            }

            case LABEL: {
                generateLabel(inst);
                break;
            }

            // ====== 导入/导出 ======
            case IMPORT: {
                generateImport(inst);
                break;
            }

            case EXPORT: {
                generateExport(inst);
                break;
            }

            // ====== 类型定义 ======
            case TYPE_DEF: {
                generateTypeDef(inst);
                break;
            }

            // ====== 元数据 ======
            case METADATA: {
                generateMetadata(inst);
                break;
            }

            // ====== NOP ======
            case NOP: {
                generateNop(inst);
                break;
            }

            default: {
                appendLine(runtime.generateComment("TODO: " + opCode.name()));
                break;
            }
        }
    }

    /**
     * 生成代码块加载代码
     */
    private void generateBlockLoadingCode(IRBasicBlock block) {
        appendLine("# Loading block: " + block.getBlockId());

        // 生成块的初始化代码
        if (block.getBlockType().equals("function")) {
            appendLine("# Function block initialization");
        } else if (block.getBlockType().equals("class")) {
            appendLine("# Class block initialization");
        } else if (block.getBlockType().equals("loop")) {
            appendLine("# Loop block initialization");
        }

        // 生成块的主体代码
        for (IRInstruction inst : block.getInstructions()) {
            generateInstruction(inst);
        }
    }

    /**
     * 生成try代码体
     */
    private void generateTryBody(IRInstruction inst) {
        appendLine("try:");
        indentLevel++;

        // 生成try块的主体
        List<Object> operands = inst.getOperands();
        if (operands != null && !operands.isEmpty()) {
            // 如果有指定的try块代码
            String tryBody = operands.get(0).toString();
            if (!tryBody.equals("pass")) {
                appendLine(tryBody);
            } else {
                appendLine("pass  # try block body");
            }
        } else {
            // 默认空try块
            appendLine("pass  # try block body");
        }

        indentLevel--;
    }

    /**
     * 生成finally代码体
     */
    private void generateFinallyBody(IRInstruction inst) {
        appendLine("finally:");
        indentLevel++;

        // 生成finally块的主体
        List<Object> operands = inst.getOperands();
        if (operands != null && !operands.isEmpty()) {
            String finallyBody = operands.get(0).toString();
            if (!finallyBody.equals("pass")) {
                appendLine(finallyBody);
            } else {
                appendLine("pass  # finally block body");
            }
        } else {
            appendLine("pass  # finally block body");
        }

        indentLevel--;
    }

    /**
     * 从IR中提取属性列表
     */
    private void extractPropertyListFromIR() {
        // 遍历所有顶级块
        for (IRBasicBlock block : currentProgram.getTopLevelBlocks()) {
            extractPropertiesFromBlock(block, "");
        }
    }

    /**
     * 从块中提取属性
     */
    private void extractPropertiesFromBlock(IRBasicBlock block, String scope) {
        // 收集当前块的属性
        List<String> properties = new ArrayList<>();

        for (IRInstruction inst : block.getInstructions()) {
            if (inst.getOpCode() == OpCode.PROP_SET ||
                inst.getOpCode() == OpCode.BEFORE_PROPS_HOOK ||
                inst.getOpCode() == OpCode.AFTER_PROPS_HOOK) {

                String propName = inst.getOperands().get(0).toString();
                properties.add(propName);
            }
        }

        // 如果有属性，添加到映射中
        if (!properties.isEmpty()) {
            String fullScope = scope.isEmpty() ? "global" : scope;
            propertyMapping.put(fullScope, properties);
        }

        // 递归处理子块
        for (IRBasicBlock child : block.getChildren()) {
            String childScope = scope.isEmpty() ?
                child.getBlockId() : scope + "." + child.getBlockId();
            extractPropertiesFromBlock(child, childScope);
        }
    }

    /**
     * 生成多异常捕获
     */
    private void generateMultiExceptionCatch(IRInstruction inst) {
        List<Object> ops = inst.getOperands();

        // 解析多个异常类型
        List<String> exTypes = new ArrayList<>();
        int typeEndIndex = ops.size() > 2 ? ops.size() - 2 : ops.size();

        for (int i = 0; i < typeEndIndex; i++) {
            exTypes.add(ops.get(i).toString());
        }

        // 确定变量名和处理器体
        String varName = "e";
        String handlerBody = "pass  # handle exception";

        if (ops.size() > typeEndIndex) {
            varName = ops.get(typeEndIndex).toString();
        }
        if (ops.size() > typeEndIndex + 1) {
            handlerBody = ops.get(typeEndIndex + 1).toString();
        }

        // 映射异常类型到 Python 类型
        String pyTypes = exTypes.stream()
            .map(op -> runtime.mapType(op.toString()))
            .collect(Collectors.joining(", "));

        appendLine("except (" + pyTypes + ") as " + varName + ":");
        indentLevel++;
        appendLine(handlerBody);
        indentLevel--;
    }

    /**
     * 生成函数定义
     */
    private void generateFunctionDefinition(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String funcName = ops.get(0).toString();
        appendLine("");

        // 重置当前函数参数列表
        currentFuncParams = new ArrayList<>();

        // 函数名转换：private 函数用下划线前缀
        String pyFuncName = "private".equals(funcName) ? "_private" : funcName;

        // 生成装饰器（如果有属性监听）
        generateFunctionDecorators(funcName);

        // 生成 def 语句
        String paramsStr = generateFunctionParameters();
        appendLine("def " + pyFuncName + "(" + paramsStr + "):");

        // 增加缩进表示函数体开始
        indentLevel++;

        // 如果有注释，添加到下一行
        if (inst.getComment() != null) {
            appendLine(runtime.generateComment(inst.getComment()));
        }

        appendLine("    pass  # Function body");
    }

    /**
     * 生成函数装饰器
     */
    private void generateFunctionDecorators(String funcName) {
        // 从属性映射中获取当前函数的属性
        List<String> properties = propertyMapping.getOrDefault(funcName, Collections.emptyList());

        // 生成 @BeforeProps 装饰器
        List<String> beforeProps = new ArrayList<>();
        List<String> afterProps = new ArrayList<>();

        for (String prop : properties) {
            // 简单的属性分类逻辑
            if (prop.startsWith("on")) {
                afterProps.add(prop);
            } else {
                beforeProps.add(prop);
            }
        }

        if (!beforeProps.isEmpty()) {
            appendLine("@BeforeProps(" + String.join(", ", beforeProps) + ")");
        }
        if (!afterProps.isEmpty()) {
            appendLine("@AfterProps(" + String.join(", ", afterProps) + ")");
        }
    }

    /**
     * 生成函数参数
     */
    private String generateFunctionParameters() {
        if (currentFuncParams == null || currentFuncParams.isEmpty()) {
            return "";
        }

        // 参数列表：param1: type1, param2: type2, ...
        return String.join(", ", currentFuncParams);
    }

    /**
     * 生成分配
     */
    private void generateAllocation(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String varName = ops.get(0).toString();
        String typeName = ops.size() > 1 ? ops.get(1).toString() : "Any";
        String pyType = runtime.mapType(typeName);

        // 获取初始值
        String initialValue = runtime.generateAllocation(typeName, Collections.singletonList(varName));

        // 生成变量声明（带类型注解）
        appendLine(varName + ": " + pyType + " = " + initialValue);

        // 如果需要，添加属性监听
        Object rawProps = propertyMapping.get(varName);
        if (rawProps instanceof List) {
            @SuppressWarnings("unchecked")
            List<String> props = (List<String>) rawProps;
            for (String prop : props) {
                appendLine(runtime.generateBeforePropsHook(prop, varName));
            }
        }
    }

    /**
     * 生成函数调用
     */
    private void generateFunctionCall(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String funcName = ops.get(0).toString();
        List<String> args = new ArrayList<>();

        // 收集参数（跳过第一个参数，即函数名）
        for (int i = 1; i < ops.size(); i++) {
            args.add(ops.get(i).toString());
        }

        // 处理特殊的"flow to"语句
        if ("flow to".equals(funcName) && !args.isEmpty()) {
            generateFlowToStatement(args);
            return;
        }

        // 生成函数调用
        String call = runtime.generateFunctionCall(funcName, args);

        // 如果有返回值需要使用，生成赋值
        String resultVar = getStackTopVariable();
        if (resultVar != null) {
            appendLine(resultVar + " = " + call);
        } else {
            appendLine(call);
        }
    }

    /**
     * 生成"flow to"语句
     */
    private void generateFlowToStatement(List<String> args) {
        if (args.isEmpty()) return;

        String target = args.get(0).toString();

        // 根据不同的目标类型生成相应的代码
        if (target.startsWith("cleanup")) {
            // 流控制到清理代码
            appendLine("goto " + target);
        } else if (target.startsWith("error")) {
            // 流控制到错误处理
            appendLine("raise Exception('Flow to: " + target + "')");
        } else {
            // 普通标签跳转
            appendLine("if True:  # Flow to " + target);
            indentLevel++;
            appendLine("pass");
            indentLevel--;
        }
    }

    // ========== 其他生成方法 ==========

    private void generateStoreVariable(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String varName = ops.get(0).toString();
        appendLine(varName + " = " + getStackTopVariable());
        if (inst.getComment() != null) {
            replaceLastLineComment(inst.getComment());
        }
    }

    private void generateLoadVariable(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String varName = ops.get(0).toString();
        updateStackTopVariable("__stack_top");
        appendLine("__stack_top = " + varName);
    }

    private void generateLoadConstant(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String value = ops.get(0).toString();
        updateStackTopVariable("__stack_top");
        appendLine("__stack_top = " + value);
    }

    private void generateArithmeticOperation(IRInstruction inst) {
        String op = opCodeToOperator(inst.getOpCode());
        String pyOp = mapOperatorForPython(op);
        appendLine("__stack_top = __left " + pyOp + " __right");
    }

    private void generateComparisonOperation(IRInstruction inst) {
        String op = opCodeToOperator(inst.getOpCode());
        appendLine("__stack_top = __left " + op + " __right");
    }

    private void generateLogicalOperation(IRInstruction inst) {
        switch (inst.getOpCode()) {
            case AND: appendLine("__stack_top = __left and __right"); break;
            case OR: appendLine("__stack_top = __left or __right"); break;
            case NOT: appendLine("__stack_top = not __operand"); break;
        }
    }

    private void generateScopeEnter(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String scopeName = ops.get(0).toString();
        appendLine(runtime.generateComment("=== Scope: " + scopeName + " ==="));
        indentLevel++;
    }

    private void generateScopeExit(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String scopeName = ops.get(0).toString();
        appendLine(runtime.generateComment("=== Exit scope: " + scopeName + " ==="));
        indentLevel = Math.max(0, indentLevel - 1);
    }

    private void generateJump(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String label = ops.get(0).toString();
        if ("flow to".equals(label)) {
            appendLine("pass  # Flow control implemented in FUNC_CALL");
        } else {
            appendLine("goto " + label);
        }
    }

    private void generateConditionalJump(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String label = ops.get(0).toString();
        boolean jumpIfTrue = inst.getOpCode() == OpCode.JUMP_IF_TRUE;
        appendLine(runtime.generateConditionalJump(jumpIfTrue, "__condition", label));
    }

    private void generateBeforePropsHook(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String prop = ops.get(0).toString();
        appendLine(runtime.generateBeforePropsHook(prop, "__new_value"));
        if (inst.getComment() != null) {
            replaceLastLineComment(inst.getComment());
        }
    }

    private void generateAfterPropsHook(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String prop = ops.get(0).toString();
        appendLine(runtime.generateAfterPropsHook(prop, "__old_value", "__new_value"));
    }

    private void generateBeforeNameHook(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String methodName = ops.get(0).toString();
        String target = ops.size() > 1 ? ops.get(1).toString() : "self";
        appendLine(runtime.generateConstructorHook(methodName, target));
    }

    private void generateAfterNameHook(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String methodName = ops.get(0).toString();
        String target = ops.size() > 1 ? ops.get(1).toString() : "self";
        appendLine(runtime.generateDestructorHook(methodName, target));
    }

    private void generatePropertySet(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String prop = ops.get(0).toString();
        appendLine(prop + " = __new_value");
    }

    private void generateArrayCreation(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String elemType = ops.get(0).toString();
        String size = ops.size() > 1 ? ops.get(1).toString() : "0";
        appendLine("__stack_top = " + runtime.generateArrayCreation(elemType, size));
    }

    private void generateArrayGet(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String arrName = ops.get(0).toString();
        String index = ops.size() > 1 ? ops.get(1).toString() : "0";
        appendLine("if 0 <= " + index + " < len(" + arrName + "):");
        indentLevel++;
        appendLine("__stack_top = " + runtime.generateArrayGet(arrName, index));
        indentLevel--;
        appendLine("else:");
        indentLevel++;
        appendLine("raise IndexError('Array index out of bounds')");
        indentLevel--;
    }

    private void generateArraySet(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String arrName = ops.get(0).toString();
        String index = ops.size() > 1 ? ops.get(1).toString() : "0";
        String value = ops.size() > 2 ? ops.get(2).toString() : "__stack_top";
        appendLine("if 0 <= " + index + " < len(" + arrName + "):");
        indentLevel++;
        appendLine(runtime.generateArraySet(arrName, index, value));
        indentLevel--;
        appendLine("else:");
        indentLevel++;
        appendLine("raise IndexError('Array index out of bounds')");
        indentLevel--;
    }

    private void generateDeallocation(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String varName = ops.get(0).toString();
        appendLine(runtime.generateDeallocation(varName));
    }

    private void generateReturn(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String retVal = ops.isEmpty() ? null : ops.get(0).toString();
        appendLine(runtime.generateReturn(retVal));
    }

    private void generateNormalFlowBegin(IRInstruction inst) {
        appendLine(runtime.generateComment("=== Normal Flow Begin ==="));
    }

    private void generateNormalFlowEnd(IRInstruction inst) {
        appendLine(runtime.generateComment("=== Normal Flow End ==="));
    }

    private void generateExceptionCatch(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String exType = ops.get(0).toString();
        String varName = ops.size() > 1 ? ops.get(1).toString() : "e";
        String handlerBody = ops.size() > 2 ? ops.get(2).toString() : "pass  # handle exception";
        appendLine(runtime.generateCatchBlock(exType, varName, handlerBody));
    }

    private void generateExceptionThrows(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String exType = ops.get(0).toString();
        appendLine(runtime.generateComment("Raises: " + runtime.mapType(exType)));
    }

    private void generateLabel(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String labelName = ops.get(0).toString();
        appendLine(labelName + ":");
    }

    private void generateImport(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String module = ops.get(0).toString();
        String symbol = ops.size() > 1 ? ops.get(1).toString() : null;
        String importLine = runtime.generateImport(module, symbol);
        appendLine(importLine);
        importedModules.add(importLine);
    }

    private void generateExport(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String symbol = ops.get(0).toString();
        appendLine(runtime.generateExport(symbol));
    }

    private void generateTypeDef(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        String typeName = ops.get(0).toString();
        appendLine("");
        appendLine(runtime.generateTypeDefinitionHeader(typeName, "public"));
        indentLevel++;

        if (inst.getComment() != null) {
            appendLine(runtime.generateComment(inst.getComment()));
        }

        appendLine("    pass  # Type definition");
    }

    private void generateMetadata(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        appendLine(runtime.generateComment("metadata: " +
            ops.stream().map(Object::toString).collect(Collectors.joining(", "))));
    }

    private void generateNop(IRInstruction inst) {
        List<Object> ops = inst.getOperands();
        if (!ops.isEmpty()) {
            appendLine(runtime.generateComment(ops.get(0).toString()));
        } else {
            appendLine("pass");
        }
    }

    // ========== 辅助方法 ==========

    private String getFieldName(String propertyPath) {
        int lastDot = propertyPath.lastIndexOf('.');
        return lastDot > 0 ? propertyPath.substring(lastDot + 1) : propertyPath;
    }

    private String getStackTopVariable() {
        return "__stack_top";
    }

    private void updateStackTopVariable(String newVar) {
        this.stackTopVar = newVar;
    }

    private void appendLine(String line) {
        if (line == null || line.isEmpty()) {
            output.append("\n");
            return;
        }

        if (line.contains("\n")) {
            for (String subLine : line.split("\n", -1)) {
                if (!subLine.isEmpty()) {
                    String indent = "    ".repeat(Math.max(0, indentLevel));
                    output.append(indent).append(subLine).append("\n");
                }
            }
            return;
        }

        String indent = "    ".repeat(Math.max(0, indentLevel));
        output.append(indent).append(line).append("\n");
    }

    private void replaceLastLineComment(String comment) {
        int lastNewline = output.lastIndexOf("\n", output.length() - 2);
        if (lastNewline >= 0) {
            output.insert(output.length() - 1, "  " + runtime.generateComment(comment));
        }
    }

    private String opCodeToOperator(OpCode opCode) {
        switch (opCode) {
            case ADD: return "+";
            case SUB: return "-";
            case MUL: return "*";
            case DIV: return "/";
            case MOD: return "%";
            case CMP_EQ: return "==";
            case CMP_NE: return "!=";
            case CMP_LT: return "<";
            case CMP_GT: return ">";
            case CMP_LE: return "<=";
            case CMP_GE: return ">=";
            default: return "?";
        }
    }

    private String mapOperatorForPython(String op) {
        switch (op) {
            case "&&": return "and";
            case "||": return "or";
            case "!":  return "not";
            default:   return op;
        }
    }
}