package claw.compiler.binding.c;

import claw.compiler.binding.TargetCodeGenerator;
import claw.compiler.binding.TargetRuntime;
import claw.compiler.generators.ClawIR;
import claw.compiler.generators.IRGenerator;
import claw.compiler.generators.IRGenerator.IRBasicBlock;
import claw.compiler.generators.IRGenerator.IRInstruction;
import claw.compiler.generators.IRGenerator.OpCode;

import java.util.*;
import java.util.stream.Collectors;

import com.claw.binding.GenerationConfig;
import com.claw.binding.GenerationResult;

/**
 * C 目标语言代码生成器
 * 
 * 遍历 ClawIR 中的所有指令，调用 CRuntime 方法生成 C11 代码。
 * 
 * C 语言关键差异点：
 *   1. 显式内存管理（malloc/free）
 *   2. 无原生异常 → setjmp/longjmp + CLAW_TRY/CLAW_CATCH 宏
 *   3. 原生 goto → 完美映射 Claw 的 flow-to
 *   4. struct + 函数指针 → 模拟面向对象
 *   5. 头文件/源文件分离
 *   6. 函数前向声明
 *   7. 字符串为 char*，需手动管理
 */
public class CCodeGenerator implements TargetCodeGenerator {

    private final CRuntime runtime;
    private StringBuilder output;
    private StringBuilder headerOutput;   // 头文件输出
    private int indentLevel;

    // 收集信息用于生成头文件
    private final List<String> functionPrototypes;
    private final List<String> typeDefinitions;
    private final List<String> allocatedVars; // 跟踪已分配的变量（用于自动释放）

    public CCodeGenerator() {
        this.runtime = new CRuntime();
        this.functionPrototypes = new ArrayList<>();
        this.typeDefinitions = new ArrayList<>();
        this.allocatedVars = new ArrayList<>();
    }

    @Override
    public TargetRuntime getRuntime() {
        return runtime;
    }

    @Override
    public String getLanguageName() {
        return "C";
    }

    @Override
    public String getFileExtension() {
        return ".c";
    }

    /**
     * 获取生成的头文件内容
     */
    public String getHeaderOutput() {
        return headerOutput != null ? headerOutput.toString() : "";
    }

    @Override
    public String generate(ClawIR ir) {
        output = new StringBuilder();
        headerOutput = new StringBuilder();
        indentLevel = 0;
        functionPrototypes.clear();
        typeDefinitions.clear();
        allocatedVars.clear();

        IRGenerator.IRProgram program = ir.getIrProgram();

        // ===== 源文件 (.c) =====

        // 1. 文件头注释
        appendLine("/**");
        appendLine(" * Auto-generated by Claw Compiler");
        appendLine(" * Target: C11");
        appendLine(" * Source: " + program.getSourceFileName());
        appendLine(" */");
        appendLine("");

        // 2. #include 指令
        for (String inc : runtime.getRequiredImports()) {
            appendLine("#include " + inc);
        }
        appendLine("#include <stdarg.h>");
        appendLine("");

        // 3. 元数据（系统注解 → Doxygen 注释）
        Map metadata = program.getMetadata();
        if (metadata != null && !metadata.isEmpty()) {
            appendLine(runtime.generateDocComment(metadata));
            appendLine("");
        }

        // 4. 运行时辅助代码
        appendLine(runtime.generateRuntimeHelpers());
        appendLine("");

        // 5. 第一遍扫描：收集类型定义和函数原型
        for (IRBasicBlock topBlock : program.getTopLevelBlocks()) {
            collectDeclarations(topBlock);
        }

        // 6. 输出前向声明
        if (!functionPrototypes.isEmpty()) {
            appendLine("/* --- Forward Declarations --- */");
            for (String proto : functionPrototypes) {
                appendLine(proto);
            }
            appendLine("");
        }

        // 7. 第二遍：生成完整代码
        for (IRBasicBlock topBlock : program.getTopLevelBlocks()) {
            generateBlock(topBlock);
        }

        // 8. main 函数入口
        appendLine("");
        appendLine("int main(int argc, char* argv[]) {");
        indentLevel++;
        appendLine(runtime.generateComment("Claw program entry point"));
        appendLine("return 0;");
        indentLevel--;
        appendLine("}");

        // ===== 头文件 (.h) =====
        String moduleName = program.getSourceFileName() != null ? program.getSourceFileName() : "claw_output";
        headerOutput = new StringBuilder(
            runtime.generateHeaderFile(moduleName, functionPrototypes, typeDefinitions)
        );

        return output.toString();
    }

    // ==================== 第一遍扫描：收集声明 ====================

    private void collectDeclarations(IRBasicBlock block) {
        for (IRInstruction inst : block.getInstructions()) {
            OpCode op = inst.getOpCode();
            List<Object> ops = inst.getOperands();

            if (op == OpCode.FUNC_DEF) {
                String funcName = ops.get(0).toString();
                // 简化版原型
                String proto = runtime.generateFunctionPrototype(
                    "public", "void", funcName, Collections.emptyList(), null
                );
                functionPrototypes.add(proto);
            } else if (op == OpCode.TYPE_DEF) {
                String typeName = ops.get(0).toString();
                String typeDef = "typedef struct " + typeName + " " + typeName + ";";
                typeDefinitions.add(typeDef);
            }
        }

        if (block.getChildren() != null) {
            for (IRBasicBlock child : block.getChildren()) {
                collectDeclarations(child);
            }
        }
    }

    // ==================== 第二遍：生成代码 ====================

    private void generateBlock(IRBasicBlock block) {
        for (IRInstruction inst : block.getInstructions()) {
            generateInstruction(inst);
        }
        if (block.getChildren() != null) {
            for (IRBasicBlock child : block.getChildren()) {
                generateBlock(child);
            }
        }
    }

    // ==================== 指令分派 ====================

    private void generateInstruction(IRInstruction inst) {
        OpCode opCode = inst.getOpCode();
        List<Object> ops = inst.getOperands();

        switch (opCode) {

            // ====== 函数定义 ======
            case FUNC_DEF: {
                String funcName = ops.get(0).toString();
                appendLine("");
                appendLine(runtime.generateFunctionHeader(
                    "public", "void", funcName,
                    Collections.emptyList(), Collections.emptyList()
                ));
                indentLevel++;
                allocatedVars.clear(); // 新函数作用域清空
                break;
            }

            case FUNC_END: {
                // 函数结束前：释放所有已分配的内存
                if (!allocatedVars.isEmpty()) {
                    appendLine("");
                    appendLine(runtime.generateComment("Auto cleanup: release allocated memory"));
                    for (String var : allocatedVars) {
                        appendLine(runtime.generateDeallocation(var));
                    }
                    allocatedVars.clear();
                }
                indentLevel = Math.max(0, indentLevel - 1);
                appendLine(runtime.generateFunctionFooter());
                appendLine("");
                break;
            }

            // ====== 内存管理 ======
            case ALLOC: {
                String varName = ops.get(0).toString();
                String typeName = ops.size() > 1 ? ops.get(1).toString() : "Any";
                String alloc = runtime.generateAllocation(typeName, null);
                appendLine(runtime.generateVariableDeclaration(false, typeName, varName, alloc));

                // 非基本类型需要跟踪以便自动释放
                if (!isBasicType(typeName)) {
                    allocatedVars.add(varName);
                    // NULL 检查
                    appendLine(runtime.generateIf(varName + " == NULL"));
                    indentLevel++;
                    appendLine("fprintf(stderr, \"Memory allocation failed for " + varName + "\\");
                    appendLine(runtime.generateReturn(""));
                    indentLevel--;
                    appendLine(runtime.getBlockClose());
                }
                break;
            }

            case DEALLOC: {
                String varName = ops.get(0).toString();
                appendLine(runtime.generateDeallocation(varName));
                allocatedVars.remove(varName);
                break;
            }

            // ====== 变量操作 ======
            case STORE_VAR: {
                String varName = ops.get(0).toString();
                appendLine(varName + " = __stack_top" + runtime.getStatementTerminator());
                break;
            }

            case LOAD_VAR: {
                String varName = ops.get(0).toString();
                appendLine("__stack_top = " + varName + runtime.getStatementTerminator());
                break;
            }

            case LOAD_CONST: {
                String value = ops.get(0).toString();
                appendLine("__stack_top = " + value + runtime.getStatementTerminator());
                break;
            }

            // ====== 运算 ======
            case ADD: case SUB: case MUL: case DIV: case MOD: {
                String op = opCodeToOperator(opCode);
                appendLine("__stack_top = __left " + op + " __right" + runtime.getStatementTerminator());
                break;
            }

            case CMP_EQ: case CMP_NE: case CMP_LT: case CMP_GT:
            case CMP_LE: case CMP_GE: {
                String op = opCodeToOperator(opCode);
                appendLine("__stack_top = __left " + op + " __right" + runtime.getStatementTerminator());
                break;
            }

            case AND: {
                appendLine("__stack_top = __left && __right" + runtime.getStatementTerminator());
                break;
            }

            case OR: {
                appendLine("__stack_top = __left || __right" + runtime.getStatementTerminator());
                break;
            }

            case NOT: {
                appendLine("__stack_top = !__operand" + runtime.getStatementTerminator());
                break;
            }

            // ====== 作用域 ======
            case SCOPE_ENTER: {
                String scopeName = ops.get(0).toString();
                appendLine(runtime.generateScopeEnter(scopeName));
                indentLevel++;
                break;
            }

            case SCOPE_EXIT: {
                indentLevel = Math.max(0, indentLevel - 1);
                String scopeName = ops.get(0).toString();
                appendLine(runtime.generateScopeExit(scopeName));
                break;
            }

            // ====== 控制流 ======
            case JUMP_IF_TRUE: {
                appendLine(runtime.generateIf("__condition"));
                indentLevel++;
                break;
            }

            case JUMP_IF_FALSE: {
                appendLine(runtime.generateIf("!__condition"));
                indentLevel++;
                break;
            }

            // ====== 属性监听钩子 ======
            case BEFORE_PROPS_HOOK: {
                String prop = ops.get(0).toString();
                appendLine(runtime.generateBeforePropsHook(prop, "__new_value"));
                break;
            }

            case AFTER_PROPS_HOOK: {
                String prop = ops.get(0).toString();
                appendLine(runtime.generateAfterPropsHook(prop, "__old_value", "__new_value"));
                break;
            }

            case BEFORE_NAME_HOOK: {
                String methodName = ops.get(0).toString();
                String target = ops.size() > 1 ? ops.get(1).toString() : "self";
                appendLine(runtime.generateConstructorHook(methodName, target));
                break;
            }

            case AFTER_NAME_HOOK: {
                String methodName = ops.get(0).toString();
                String target = ops.size() > 1 ? ops.get(1).toString() : "self";
                appendLine(runtime.generateComment("Register destructor: " + methodName));
                appendLine(runtime.generateDestructorHook(methodName, target));
                break;
            }

            // ====== 属性读写（struct 字段） ======
            case PROP_GET: {
                String objField = ops.get(0).toString();
                int dotIdx = objField.lastIndexOf('.');
                if (dotIdx > 0) {
                    String obj = objField.substring(0, dotIdx);
                    String field = objField.substring(dotIdx + 1);
                    appendLine("__stack_top = " +
                        runtime.generatePropertyGet(obj, field) +
                        runtime.getStatementTerminator());
                } else {
                    appendLine("__stack_top = " + objField + runtime.getStatementTerminator());
                }
                break;
            }

            case PROP_SET: {
                String prop = ops.get(0).toString();
                int dotIdx = prop.lastIndexOf('.');
                if (dotIdx > 0) {
                    String obj = prop.substring(0, dotIdx);
                    String field = prop.substring(dotIdx + 1);
                    appendLine(runtime.generatePropertySet(obj, field, "__new_value"));
                } else {
                    appendLine(prop + " = __new_value" + runtime.getStatementTerminator());
                }
                break;
            }

            // ====== 数组 ======
            case ARRAY_NEW: {
                String elemType = ops.get(0).toString();
                String size = ops.size() > 1 ? ops.get(1).toString() : "0";
                appendLine("__stack_top = " + runtime.generateArrayCreation(elemType, size) +
                           runtime.getStatementTerminator());
                allocatedVars.add("__stack_top"); // 需要释放
                break;
            }

            case ARRAY_GET: {
                String arrName = ops.get(0).toString();
                String index = ops.size() > 1 ? ops.get(1).toString() : "0";
                appendLine("__stack_top = " + runtime.generateArrayGet(arrName, index) +
                           runtime.getStatementTerminator());
                break;
            }

            case ARRAY_SET: {
                String arrName = ops.get(0).toString();
                String index = ops.size() > 1 ? ops.get(1).toString() : "0";
                String value = ops.size() > 2 ? ops.get(2).toString() : "__stack_top";
                appendLine(runtime.generateArraySet(arrName, index, value));
                break;
            }

            // ====== 函数调用 ======
            case CALL: {
                String funcName = ops.get(0).toString();
                List<String> args = new ArrayList<>();
                for (int i = 1; i < ops.size(); i++) {
                    args.add(ops.get(i).toString());
                }
                appendLine("__stack_top = " +
                    runtime.generateFunctionCall(funcName, args) +
                    runtime.getStatementTerminator());
                break;
            }

            case RETURN: {
                // 返回前释放局部分配的内存
                if (!allocatedVars.isEmpty()) {
                    appendLine(runtime.generateComment("Cleanup before return"));
                    for (String var : allocatedVars) {
                        appendLine(runtime.generateDeallocation(var));
                    }
                }
                String retVal = ops.isEmpty() ? null : ops.get(0).toString();
                appendLine(runtime.generateReturn(retVal));
                break;
            }

            // ====== 三层操作流 ======
            case NORMAL_FLOW_BEGIN: {
                appendLine(runtime.generateComment("=== Normal Flow Begin ==="));
                appendLine("CLAW_TRY");
                indentLevel++;
                break;
            }

            case NORMAL_FLOW_END: {
                indentLevel = Math.max(0, indentLevel - 1);
                appendLine("CLAW_END_TRY;");
                appendLine(runtime.generateComment("=== Normal Flow End ==="));
                break;
            }

            case EXCEPTION_CATCH: {
                String exType = ops.get(0).toString();
                String varName = ops.size() > 1 ? ops.get(1).toString() : "e";
                String exEnum = "CLAW_EX_" + exType.toUpperCase();
                appendLine("CLAW_CATCH(" + exEnum + ")");
                indentLevel++;
                appendLine("ClawException* " + varName + " = &__claw_current_exception;");
                break;
            }

            case EXCEPTION_THROWS: {
                String exType = ops.get(0).toString();
                appendLine(runtime.generateComment("throws: " + exType));
                break;
            }

            case FLOW_TO: {
                // C 原生支持 goto！完美映射
                String target = ops.get(0).toString();
                appendLine(runtime.generateFlowTo(target));
                break;
            }

            // ====== 标签（flow-to 的目标） ======
            case LABEL: {
                String label = ops.get(0).toString();
                // 标签不缩进
                output.append(label).append(":");
                break;
            }

            // ====== 导入/导出 ======
            case IMPORT: {
                String module = ops.get(0).toString();
                appendLine(runtime.generateImport(module, null));
                break;
            }

            case EXPORT: {
                String symbol = ops.get(0).toString();
                appendLine(runtime.generateExport(symbol));
                break;
            }

            // ====== 类型定义（struct） ======
            case TYPE_DEF: {
                String typeName = ops.get(0).toString();
                appendLine("");
                appendLine(runtime.generateTypeDefinitionHeader(typeName, "public"));
                indentLevel++;
                break;
            }

            case TYPE_FIELD: {
                String fieldName = ops.get(0).toString();
                String fieldType = ops.size() > 1 ? ops.get(1).toString() : "Any";
                String visibility = ops.size() > 2 ? ops.get(2).toString() : "public";
                appendLine(runtime.generateTypeField(fieldName, fieldType, visibility));
                break;
            }

            case TYPE_END: {
                String typeName = ops.get(0).toString();
                indentLevel = Math.max(0, indentLevel - 1);
                appendLine(runtime.generateCompleteTypeDefinition(typeName));
                appendLine("");

                // 生成构造/析构辅助函数
                appendLine(generateStructConstructor(typeName));
                appendLine(generateStructDestructor(typeName));
                break;
            }

            // ====== 元数据 ======
            case METADATA: {
                appendLine(runtime.generateComment("metadata: " +
                    ops.stream().map(Object::toString).collect(Collectors.joining(", "))));
                break;
            }

            // ====== NOP ======
            case NOP: {
                if (!ops.isEmpty()) {
                    appendLine(runtime.generateComment(ops.get(0).toString()));
                }
                // C 中不需要空语句
                break;
            }

            default: {
                appendLine(runtime.generateComment("TODO: " + opCode.name()));
                break;
            }
        }
    }

    // ==================== C 特有的辅助生成 ====================

    /**
     * 为 struct 生成构造函数
     */
    private String generateStructConstructor(String typeName) {
        StringBuilder sb = new StringBuilder();
        sb.append(typeName).append("* ").append(typeName).append("_create(void) {");
        sb.append("    ").append(typeName).append("* self = (")
          .append(typeName).append("*)malloc(sizeof(").append(typeName).append("));");
        sb.append("    if (self == NULL) {");
        sb.append("        fprintf(stderr, \"Failed to allocate ").append(typeName).append("\\");
        sb.append("        return NULL;");
        sb.append("    }");
        sb.append("    memset(self, 0, sizeof(").append(typeName).append("));");
        sb.append("    return self;");
        sb.append("}");
        return sb.toString();
    }

    /**
     * 为 struct 生成析构函数
     */
    private String generateStructDestructor(String typeName) {
        StringBuilder sb = new StringBuilder();
        sb.append("void ").append(typeName).append("_destroy(").append(typeName).append("* self) {");
        sb.append("    if (self != NULL) {");
        sb.append("        ").append(runtime.generateComment("TODO: free nested allocations")).append("\n");
        sb.append("        free(self);");
        sb.append("    }");
        sb.append("}");
        return sb.toString();
    }

    /**
     * 判断是否为基本类型（不需要 malloc/free）
     */
    private boolean isBasicType(String typeName) {
        switch (typeName) {
            case "Int": case "Float": case "Bool": case "Void":
                return true;
            default:
                return false;
        }
    }

    // ==================== 通用辅助 ====================

    private void appendLine(String line) {
        if (line == null || line.isEmpty()) {
            output.append("\n");
            return;
        }
        // 多行内容处理
        if (line.contains("\n")) {
            for (String subLine : line.split("\n", -1)) {
                if (!subLine.isEmpty()) {
                    String indent = "    ".repeat(Math.max(0, indentLevel));
                    output.append(indent).append(subLine).append("\n");
                } else {
                    output.append("\n");
                }
            }
            return;
        }
        String indent = "    ".repeat(Math.max(0, indentLevel));
        output.append(indent).append(line).append("\n");
    }

    private String opCodeToOperator(OpCode opCode) {
        switch (opCode) {
            case ADD: return "+";
            case SUB: return "-";
            case MUL: return "*";
            case DIV: return "/";
            case MOD: return "%";
            case CMP_EQ: return "==";
            case CMP_NE: return "!=";
            case CMP_LT: return "<";
            case CMP_GT: return ">";
            case CMP_LE: return "<=";
            case CMP_GE: return ">=";
            default: return "?";
        }
    }

    @Override
    public GenerationResult generate(com.claw.ir.ClawIR ir, GenerationConfig defaultConfig) {
        GenerationResult result = new GenerationResult();
        if (ir == null) {
            result.addWarning("No IR provided for C code generation.");
            return result;
        }
        String fileName = "claw_output" + getFileExtension();
        result.addFile(fileName, "// C code generation is not supported for com.claw.ir.ClawIR yet\n");
        return result;
    }
}
